/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'in {0}',
	'now',
	'{0} sec ago',
	'{0} secs ago',
	'{0} sec',
	'{0} secs',
	'{0} min ago',
	'{0} mins ago',
	'{0} min',
	'{0} mins',
	'{0} hr ago',
	'{0} hrs ago',
	'{0} hr',
	'{0} hrs',
	'{0} day ago',
	'{0} days ago',
	'{0} day',
	'{0} days',
	'{0} wk ago',
	'{0} wks ago',
	'{0} wk',
	'{0} wks',
	'{0} mo ago',
	'{0} mos ago',
	'{0} mo',
	'{0} mos',
	'{0} yr ago',
	'{0} yrs ago',
	'{0} yr',
	'{0} yrs'
]);