/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'View icon of the outline view.',
	"Outline",
	"Outline",
	"Render Outline Elements with Icons.",
	"Show Errors & Warnings on Outline Elements.",
	"Use colors for Errors & Warnings.",
	"Use badges for Errors & Warnings.",
	"When enabled outline shows `file`-symbols.",
	"When enabled outline shows `module`-symbols.",
	"When enabled outline shows `namespace`-symbols.",
	"When enabled outline shows `package`-symbols.",
	"When enabled outline shows `class`-symbols.",
	"When enabled outline shows `method`-symbols.",
	"When enabled outline shows `property`-symbols.",
	"When enabled outline shows `field`-symbols.",
	"When enabled outline shows `constructor`-symbols.",
	"When enabled outline shows `enum`-symbols.",
	"When enabled outline shows `interface`-symbols.",
	"When enabled outline shows `function`-symbols.",
	"When enabled outline shows `variable`-symbols.",
	"When enabled outline shows `constant`-symbols.",
	"When enabled outline shows `string`-symbols.",
	"When enabled outline shows `number`-symbols.",
	"When enabled outline shows `boolean`-symbols.",
	"When enabled outline shows `array`-symbols.",
	"When enabled outline shows `object`-symbols.",
	"When enabled outline shows `key`-symbols.",
	"When enabled outline shows `null`-symbols.",
	"When enabled outline shows `enumMember`-symbols.",
	"When enabled outline shows `struct`-symbols.",
	"When enabled outline shows `event`-symbols.",
	"When enabled outline shows `operator`-symbols.",
	"When enabled outline shows `typeParameter`-symbols."
]);