ARG BASE

FROM $BASE

ARG AUTHOR
ARG VERSION
LABEL maintainer=${AUTHOR} version=${VERSION}

ENV CHECK_FILE=.local/share/code-server/languagepacks.json

COPY ./.local/share/code-server/ /data/input/.local/share/code-server/

ARG GOVERSION
ARG NODEVERSION
ARG YARNVERSION
COPY ./go$GOVERSION/ /data/input/go$GOVERSION/
COPY ./node-$NODEVERSION/ /data/input/node-$NODEVERSION/
COPY ./yarn-$YARNVERSION/ /data/input/yarn-$YARNVERSION/

COPY ./go/bin/ /data/input/go/bin/

COPY ./.bashrc /data/input/.bashrc
