/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'binaryFileEditor',
	'hotExit.off',
	'hotExit.onExit',
	'hotExit.onExitAndWindowClose',
	'hotExit',
	'hotExit.off',
	'hotExit.onExitAndWindowCloseBrowser',
	'hotExit',
	'filesConfigurationTitle',
	'exclude',
	'files.exclude.boolean',
	'files.exclude.when',
	'associations',
	'encoding',
	'autoGuessEncoding',
	'eol.LF',
	'eol.CRLF',
	'eol.auto',
	'eol',
	'useTrash',
	'trimTrailingWhitespace',
	'insertFinalNewline',
	'trimFinalNewlines',
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'files.autoSave.off' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'files.autoSave.afterDelay' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'files.autoSave.onFocusChange' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'files.autoSave.onWindowChange' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'autoSave' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'autoSaveDelay' },
	'watcherExclude',
	'defaultLanguage',
	'maxMemoryForLargeFilesMB',
	'files.restoreUndoStack',
	'askUser',
	'overwriteFileOnDisk',
	'files.saveConflictResolution',
	'files.simpleDialog.enable',
	'formatOnSave',
	{ key: 'everything', comment: ['This is the description of an option'] },
	{ key: 'modification', comment: ['This is the description of an option'] },
	'formatOnSaveMode',
	'explorerConfigurationTitle',
	{ key: 'openEditorsVisible', comment: ['Open is an adjective'] },
	{ key: 'openEditorsSortOrder', comment: ['Open is an adjective'] },
	'sortOrder.editorOrder',
	'sortOrder.alphabetical',
	'autoReveal.on',
	'autoReveal.off',
	'autoReveal.focusNoScroll',
	'autoReveal',
	'enableDragAndDrop',
	'confirmDragAndDrop',
	'confirmDelete',
	'sortOrder.default',
	'sortOrder.mixed',
	'sortOrder.filesFirst',
	'sortOrder.type',
	'sortOrder.modified',
	'sortOrder',
	'explorer.decorations.colors',
	'explorer.decorations.badges',
	'simple',
	'smart',
	'explorer.incrementalNaming',
	'compressSingleChildFolders'
]);