/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Binary File Editor",
	'Disable hot exit. A prompt will show when attempting to close a window with dirty files.',
	'Hot exit will be triggered when the last window is closed on Windows/Linux or when the `workbench.action.quit` command is triggered (command palette, keybinding, menu). All windows without folders opened will be restored upon next launch. A list of previously opened windows with unsaved files can be accessed via `File > Open Recent > More...`',
	'Hot exit will be triggered when the last window is closed on Windows/Linux or when the `workbench.action.quit` command is triggered (command palette, keybinding, menu), and also for any window with a folder opened regardless of whether it\'s the last window. All windows without folders opened will be restored upon next launch. A list of previously opened windows with unsaved files can be accessed via `File > Open Recent > More...`',
	"Controls whether unsaved files are remembered between sessions, allowing the save prompt when exiting the editor to be skipped.",
	'Disable hot exit. A prompt will show when attempting to close a window with dirty files.',
	'Hot exit will be triggered when the browser quits or the window or tab is closed.',
	"Controls whether unsaved files are remembered between sessions, allowing the save prompt when exiting the editor to be skipped.",
	"Files",
	"Configure glob patterns for excluding files and folders. For example, the file Explorer decides which files and folders to show or hide based on this setting. Refer to the `#search.exclude#` setting to define search specific excludes. Read more about glob patterns [here](https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options).",
	"The glob pattern to match file paths against. Set to true or false to enable or disable the pattern.",
	"Additional check on the siblings of a matching file. Use $(basename) as variable for the matching file name.",
	"Configure file associations to languages (e.g. `\"*.extension\": \"html\"`). These have precedence over the default associations of the languages installed.",
	"The default character set encoding to use when reading and writing files. This setting can also be configured per language.",
	"When enabled, the editor will attempt to guess the character set encoding when opening files. This setting can also be configured per language.",
	"LF",
	"CRLF",
	"Uses operating system specific end of line character.",
	"The default end of line character.",
	"Moves files/folders to the OS trash (recycle bin on Windows) when deleting. Disabling this will delete files/folders permanently.",
	"When enabled, will trim trailing whitespace when saving a file.",
	"When enabled, insert a final new line at the end of the file when saving it.",
	"When enabled, will trim all new lines after the final new line at the end of the file when saving it.",
	"A dirty editor is never automatically saved.",
	"A dirty editor is automatically saved after the configured `#files.autoSaveDelay#`.",
	"A dirty editor is automatically saved when the editor loses focus.",
	"A dirty editor is automatically saved when the window loses focus.",
	"Controls auto save of dirty editors. Read more about autosave [here](https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save).",
	"Controls the delay in ms after which a dirty editor is saved automatically. Only applies when `#files.autoSave#` is set to `{0}`.",
	"Configure glob patterns of file paths to exclude from file watching. Patterns must match on absolute paths (i.e. prefix with ** or the full path to match properly). Changing this setting requires a restart. When you experience Code consuming lots of CPU time on startup, you can exclude large folders to reduce the initial load.",
	"The default language mode that is assigned to new files. If configured to `${activeEditorLanguage}`, will use the language mode of the currently active text editor if any.",
	"Controls the memory available to VS Code after restart when trying to open large files. Same effect as specifying `--max-memory=NEWSIZE` on the command line.",
	"Restore the undo stack when a file is reopened.",
	"Will refuse to save and ask for resolving the save conflict manually.",
	"Will resolve the save conflict by overwriting the file on disk with the changes in the editor.",
	"A save conflict can occur when a file is saved to disk that was changed by another program in the meantime. To prevent data loss, the user is asked to compare the changes in the editor with the version on disk. This setting should only be changed if you frequently encounter save conflict errors and may result in data loss if used without caution.",
	"Enables the simple file dialog. The simple file dialog replaces the system file dialog when enabled.",
	"Format a file on save. A formatter must be available, the file must not be saved after delay, and the editor must not be shutting down.",
	"Format the whole file.",
	"Format modifications (requires source control).",
	"Controls if format on save formats the whole file or only modifications. Only applies when `#editor.formatOnSave#` is enabled.",
	"File Explorer",
	"Number of editors shown in the Open Editors pane. Setting this to 0 hides the Open Editors pane.",
	"Controls the sorting order of editors in the Open Editors pane.",
	'Editors are ordered in the same order editor tabs are shown.',
	'Editors are ordered in alphabetical order inside each editor group.',
	'Files will be revealed and selected.',
	'Files will not be revealed and selected.',
	'Files will not be scrolled into view, but will still be focused.',
	"Controls whether the explorer should automatically reveal and select files when opening them.",
	"Controls whether the explorer should allow to move files and folders via drag and drop. This setting only effects drag and drop from inside the explorer.",
	"Controls whether the explorer should ask for confirmation to move files and folders via drag and drop.",
	"Controls whether the explorer should ask for confirmation when deleting a file via the trash.",
	'Files and folders are sorted by their names, in alphabetical order. Folders are displayed before files.',
	'Files and folders are sorted by their names, in alphabetical order. Files are interwoven with folders.',
	'Files and folders are sorted by their names, in alphabetical order. Files are displayed before folders.',
	'Files and folders are sorted by their extensions, in alphabetical order. Folders are displayed before files.',
	'Files and folders are sorted by last modified date, in descending order. Folders are displayed before files.',
	"Controls sorting order of files and folders in the explorer.",
	"Controls whether file decorations should use colors.",
	"Controls whether file decorations should use badges.",
	"Appends the word \"copy\" at the end of the duplicated name potentially followed by a number",
	"Adds a number at the end of the duplicated name. If some number is already part of the name, tries to increase that number",
	"Controls what naming strategy to use when a giving a new name to a duplicated explorer item on paste.",
	"Controls whether the explorer should render folders in a compact form. In such a form, single child folders will be compressed in a combined tree element. Useful for Java package structures, for example."
]);