/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'filesCategory',
	'workspaces',
	'file',
	'copyPath',
	'copyRelativePath',
	'revealInSideBar',
	'acceptLocalChanges',
	'revertLocalChanges',
	'copyPathOfActive',
	'copyRelativePathOfActive',
	'saveAllInGroup',
	'saveFiles',
	'revert',
	'compareActiveWithSaved',
	'openToSide',
	'revert',
	'saveAll',
	'compareWithSaved',
	'compareWithSelected',
	'compareSource',
	'compareSelected',
	'close',
	'closeOthers',
	'closeSaved',
	'closeAll',
	'explorerOpenWith',
	'cut',
	'deleteFile',
	'deleteFile',
	'newFile',
	'openFile',
	{ key: 'miNewFile', comment: ['&& denotes a mnemonic'] },
	{ key: 'miSave', comment: ['&& denotes a mnemonic'] },
	{ key: 'miSaveAs', comment: ['&& denotes a mnemonic'] },
	{ key: 'miSaveAll', comment: ['&& denotes a mnemonic'] },
	{ key: 'miOpen', comment: ['&& denotes a mnemonic'] },
	{ key: 'miOpenFile', comment: ['&& denotes a mnemonic'] },
	{ key: 'miOpenFolder', comment: ['&& denotes a mnemonic'] },
	{ key: 'miOpenWorkspace', comment: ['&& denotes a mnemonic'] },
	{ key: 'miAutoSave', comment: ['&& denotes a mnemonic'] },
	{ key: 'miRevert', comment: ['&& denotes a mnemonic'] },
	{ key: 'miCloseEditor', comment: ['&& denotes a mnemonic'] },
	{ key: 'miGotoFile', comment: ['&& denotes a mnemonic'] }
]);