/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"New File",
	"New Folder",
	"Rename",
	"Delete",
	"Copy",
	"Paste",
	"Download...",
	"&&Move to Recycle Bin",
	"&&Move to Trash",
	"&&Delete",
	"You are deleting files with unsaved changes. Do you want to continue?",
	"You are deleting a folder {0} with unsaved changes in 1 file. Do you want to continue?",
	"You are deleting a folder {0} with unsaved changes in {1} files. Do you want to continue?",
	"You are deleting {0} with unsaved changes. Do you want to continue?",
	"Your changes will be lost if you don't save them.",
	"This action is irreversible!",
	"You can restore these files using the Undo command",
	"You can restore this file using the Undo command",
	"You can restore these files from the Recycle Bin.",
	"You can restore this file from the Recycle Bin.",
	"You can restore these files from the Trash.",
	"You can restore this file from the Trash.",
	"Do not ask me again",
	"Delete {0} files",
	"Delete {0}",
	"Deleting {0} files",
	"Deleting {0}",
	"Failed to delete using the Recycle Bin. Do you want to permanently delete instead?",
	"Failed to delete using the Trash. Do you want to permanently delete instead?",
	"&&Delete Permanently",
	"&&Retry",
	"Are you sure you want to delete the following {0} files/directories and their contents?",
	"Are you sure you want to delete the following {0} directories and their contents?",
	"Are you sure you want to delete the following {0} files?",
	"Are you sure you want to delete '{0}' and its contents?",
	"Are you sure you want to delete '{0}'?",
	"Are you sure you want to permanently delete the following {0} files/directories and their contents?",
	"Are you sure you want to permanently delete the following {0} directories and their contents?",
	"Are you sure you want to permanently delete the following {0} files?",
	"Are you sure you want to permanently delete '{0}' and its contents?",
	"Are you sure you want to permanently delete '{0}'?",
	"Compare Active File With...",
	"Toggle Auto Save",
	"Save All in Group",
	"Close Group",
	"Focus on Files Explorer",
	"Reveal Active File in Side Bar",
	"Open Active File in New Window",
	"The active editor must contain an openable resource.",
	"A file or folder name must be provided.",
	"A file or folder name cannot start with a slash.",
	"A file or folder **{0}** already exists at this location. Please choose a different name.",
	"The name **{0}** is not valid as a file or folder name. Please choose a different name.",
	"Leading or trailing whitespace detected in file or folder name.",
	"Compare Active File with Clipboard",
	"Clipboard ↔ {0}",
	"Retry",
	"Create {0}",
	"Creating {0}",
	"Rename {0} to {1}",
	"Renaming {0} to {1}",
	"Downloading",
	"{0} of {1} files ({2}/s)",
	"{0} ({1} of {2}, {3}/s)",
	"Download",
	"Choose Where to Download",
	"Download {0}",
	"Downloading {0}",
	"File to paste is an ancestor of the destination folder",
	"Moving {0} files",
	"Moving {0}",
	"Move {0} files",
	"Move {0}",
	"Copying {0} files",
	"Copying {0}",
	"Copy {0} files",
	"Copy {0}",
	"The file(s) to paste have been deleted or moved since you copied them. {0}"
]);