/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Close Side Bar",
	"Toggle Activity Bar Visibility",
	"Show &&Activity Bar",
	"Toggle Centered Layout",
	"&&Centered Layout",
	"Toggle Side Bar Position",
	"Move Side Bar Right",
	"Move Side Bar Left",
	"Toggle Side Bar Position",
	"Move Side Bar Right",
	"Move Side Bar Right",
	"Move Side Bar Left",
	"Move Side Bar Left",
	"&&Move Side Bar Right",
	"&&Move Side Bar Left",
	"Toggle Editor Area Visibility",
	"Show &&Editor Area",
	"&&Appearance",
	"Toggle Side Bar Visibility",
	"Hide Side Bar",
	"Hide Side Bar",
	"Show &&Side Bar",
	"Toggle Status Bar Visibility",
	"Show S&&tatus Bar",
	"Toggle Tab Visibility",
	"Toggle Zen Mode",
	"Zen Mode",
	"Toggle Menu Bar",
	"Show Menu &&Bar",
	"Reset View Locations",
	"Move View",
	"Side Bar / {0}",
	"Panel / {0}",
	"Select a View to Move",
	"Move Focused View",
	"There is no view currently focused.",
	"The currently focused view is not movable.",
	"Select a Destination for the View",
	"View: Move {0}",
	"New Panel Entry",
	"New Side Bar Entry",
	"Side Bar",
	"Panel",
	"Reset Focused View Location",
	"There is no view currently focused.",
	"Increase Current View Size",
	"Increase Editor Width",
	"Increase Editor Height",
	"Decrease Current View Size",
	"Decrease Editor Width",
	"Decrease Editor Height"
]);