/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'closeSidebar',
	'toggleActivityBar',
	{ key: 'miShowActivityBar', comment: ['&& denotes a mnemonic'] },
	'toggleCenteredLayout',
	{ key: 'miToggleCenteredLayout', comment: ['&& denotes a mnemonic'] },
	'toggleSidebarPosition',
	'moveSidebarRight',
	'moveSidebarLeft',
	'toggleSidebarPosition',
	'move sidebar right',
	'move sidebar right',
	'move sidebar left',
	'move sidebar left',
	{ key: 'miMoveSidebarRight', comment: ['&& denotes a mnemonic'] },
	{ key: 'miMoveSidebarLeft', comment: ['&& denotes a mnemonic'] },
	'toggleEditor',
	{ key: 'miShowEditorArea', comment: ['&& denotes a mnemonic'] },
	{ key: 'miAppearance', comment: ['&& denotes a mnemonic'] },
	'toggleSidebar',
	'compositePart.hideSideBarLabel',
	'compositePart.hideSideBarLabel',
	{ key: 'miShowSidebar', comment: ['&& denotes a mnemonic'] },
	'toggleStatusbar',
	{ key: 'miShowStatusbar', comment: ['&& denotes a mnemonic'] },
	'toggleTabs',
	'toggleZenMode',
	'miToggleZenMode',
	'toggleMenuBar',
	{ key: 'miShowMenuBar', comment: ['&& denotes a mnemonic'] },
	'resetViewLocations',
	'moveView',
	'sidebarContainer',
	'panelContainer',
	'moveFocusedView.selectView',
	'moveFocusedView',
	'moveFocusedView.error.noFocusedView',
	'moveFocusedView.error.nonMovableView',
	'moveFocusedView.selectDestination',
	{ key: 'moveFocusedView.title', comment: ['{0} indicates the title of the view the user has selected to move.'] },
	{ key: 'moveFocusedView.newContainerInPanel', comment: ['Creates a new top-level tab in the panel.'] },
	'moveFocusedView.newContainerInSidebar',
	'sidebar',
	'panel',
	'resetFocusedViewLocation',
	'resetFocusedView.error.noFocusedView',
	'increaseViewSize',
	'increaseEditorWidth',
	'increaseEditorHeight',
	'decreaseViewSize',
	'decreaseEditorWidth',
	'decreaseEditorHeight'
]);