/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'remove',
	'dirtyRecentlyOpenedFolder',
	'dirtyRecentlyOpenedWorkspace',
	'workspacesAndFolders',
	'folders',
	'files',
	'openRecentPlaceholderMac',
	'openRecentPlaceholder',
	'dirtyWorkspace',
	'dirtyFolder',
	'dirtyWorkspaceConfirm',
	'dirtyFolderConfirm',
	'dirtyWorkspaceConfirmDetail',
	'dirtyFolderConfirmDetail',
	'recentDirtyWorkspaceAriaLabel',
	'recentDirtyFolderAriaLabel',
	'openRecent',
	'quickOpenRecent',
	'toggleFullScreen',
	'reloadWindow',
	'about',
	'newWindow',
	'blur',
	'file',
	'miConfirmClose',
	{ key: 'miNewWindow', comment: ['&& denotes a mnemonic'] },
	{ key: 'miOpenRecent', comment: ['&& denotes a mnemonic'] },
	{ key: 'miMore', comment: ['&& denotes a mnemonic'] },
	{ key: 'miToggleFullScreen', comment: ['&& denotes a mnemonic'] },
	{ key: 'miAbout', comment: ['&& denotes a mnemonic'] }
]);