/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Remove from Recently Opened",
	"Folder With Unsaved Files",
	"Workspace With Unsaved Files",
	"folders & workspaces",
	"folders",
	"files",
	"Select to open (hold Cmd-key to force new window or Alt-key for same window)",
	"Select to open (hold Ctrl-key to force new window or Alt-key for same window)",
	"Workspace with Unsaved Files",
	"Folder with Unsaved Files",
	"Do you want to open the workspace to review the unsaved files?",
	"Do you want to open the folder to review the unsaved files?",
	"Workspaces with unsaved files cannot be removed until all unsaved files have been saved or reverted.",
	"Folders with unsaved files cannot be removed until all unsaved files have been saved or reverted.",
	"{0}, workspace with unsaved changes",
	"{0}, folder with unsaved changes",
	"Open Recent...",
	"Quick Open Recent...",
	"Toggle Full Screen",
	"Reload Window",
	"About",
	"New Window",
	"Remove keyboard focus from focused element",
	"File",
	"Confirm Before Close",
	"New &&Window",
	"Open &&Recent",
	"&&More...",
	"&&Full Screen",
	"&&About"
]);