kind: pipeline
name: docker

trigger:
  branch:
    - dev

# platform:
#   runner: 10.11.92.36

volumes:
  - name: cache
    host:
      path: /data/cache/
  - name: yarn
    host:
      path: /data/cache/yarn/
  - name: docker
    host:
      path: /var/run/docker.sock

workspace:
  base: /go
  path: src/gitlab.wodcloud.com/cloud/vscode

steps:
  - name: read-cache-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-cache:1.0
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      check: yarn.lock
      suffix: amd64
      mount:
        - ./node_modules/
        - ./release-standalone/node_modules/
        - ./release-standalone/vendor/modules/code-oss-dev/node_modules/
        - ./test/node_modules/
        - ./vendor/modules/

  - name: build-node-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-node:14.18.1-bullseye-amd64
    volumes:
      - name: yarn
        path: /usr/local/share/.cache/yarn
    commands:
      - yarn
      - yarn build
      - yarn build:vscode
      - yarn release
      - yarn release:standalone
      - yarn test:standalone-release
      - yarn package

  - name: store-cache-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-cache:1.0
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      check: yarn.lock
      suffix: amd64
      mount:
      mount:
        - ./node_modules/
        - ./release-standalone/node_modules/
        - ./release-standalone/vendor/modules/code-oss-dev/node_modules/
        - ./test/node_modules/
        - ./vendor/modules/

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/debian:bullseye-vscode
      repo: wod/awecloud-vscode
      version: "v3.12.0"
      channel: alpha-amd64
      args: "TARGETOS=linux,TARGETARCH=amd64"
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: clean-node-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-node:14.18.1-bullseye
    commands:
      - rm -rf ./release-packages/
      - rm -rf ./release-standalone/node_modules/
      - rm -rf ./release-standalone/vendor/modules/code-oss-dev/node_modules/
      - rm -rf ./test/node_modules/

  - name: read-cache-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-cache:1.0
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      check: yarn.lock
      suffix: arm64
      mount:
        - ./release-standalone/node_modules/
        - ./release-standalone/vendor/modules/code-oss-dev/node_modules/
        - ./test/node_modules/

  - name: build-node-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-node:14.18.1-bullseye-arm64
    volumes:
      - name: yarn
        path: /usr/local/share/.cache/yarn
    commands:
      - yarn release:standalone
      - yarn test:standalone-release
      - yarn package

  - name: store-cache-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-cache:1.0
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      check: yarn.lock
      suffix: arm64
      mount:
        - ./release-standalone/node_modules/
        - ./release-standalone/vendor/modules/code-oss-dev/node_modules/
        - ./test/node_modules/

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/debian:bullseye-vscode-arm64
      repo: wod/awecloud-vscode
      version: "v3.12.0"
      channel: alpha-arm64
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:v1.2.3
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      platforms: linux/amd64,linux/arm64
      template: registry.cn-qingdao.aliyuncs.com/wod/awecloud-vscode:v3.12.0-alpha-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/awecloud-vscode:v3.12.0-alpha
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: harbor

trigger:
  branch:
    - master

platform:
  runner: 10.11.92.36

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: harbor-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/awecloud-vscode:v3.12.0-alpha-amd64
      target: registry.cn-qingdao.aliyuncs.com/wod/awecloud-vscode:v3.12.0-amd64
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/awecloud-vscode:v3.12.0-alpha-arm64
      target: registry.cn-qingdao.aliyuncs.com/wod/awecloud-vscode:v3.12.0-arm64
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:v1.2.3
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      platforms: linux/amd64,linux/arm64
      template: registry.cn-qingdao.aliyuncs.com/wod/awecloud-vscode:v3.12.0-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/awecloud-vscode:v3.12.0
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  path: devops-registry-aliyun
  name: USERNAME

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  path: devops-registry-aliyun
  name: PASSWORD
