/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'workbench.editor.titleScrollbarSizing.default',
	'workbench.editor.titleScrollbarSizing.large',
	'tabScrollbarHeight',
	'showEditorTabs',
	'wrapTabs',
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'scrollToSwitchTabs' },
	'highlightModifiedTabs',
	'decorations.badges',
	'decorations.colors',
	'workbench.editor.labelFormat.default',
	'workbench.editor.labelFormat.short',
	'workbench.editor.labelFormat.medium',
	'workbench.editor.labelFormat.long',
	{
					comment: ['This is the description for a setting. Values surrounded by parenthesis are not to be translated.'],
					key: 'tabDescription'
				},
	'workbench.editor.untitled.labelFormat.content',
	'workbench.editor.untitled.labelFormat.name',
	{
					comment: ['This is the description for a setting. Values surrounded by parenthesis are not to be translated.'],
					key: 'untitledLabelFormat'
				},
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'untitledHint' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'editorTabCloseButton' },
	'workbench.editor.tabSizing.fit',
	'workbench.editor.tabSizing.shrink',
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'tabSizing' },
	'workbench.editor.pinnedTabSizing.normal',
	'workbench.editor.pinnedTabSizing.compact',
	'workbench.editor.pinnedTabSizing.shrink',
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'pinnedTabSizing' },
	'workbench.editor.splitSizingDistribute',
	'workbench.editor.splitSizingSplit',
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'splitSizing' },
	'splitOnDragAndDrop',
	'focusRecentEditorAfterClose',
	'showIcons',
	'enablePreview',
	'enablePreviewFromQuickOpen',
	'enablePreviewFromCodeNavigation',
	'closeOnFileDelete',
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'editorOpenPositioning' },
	'sideBySideDirection',
	'closeEmptyGroups',
	'revealIfOpen',
	'mouseBackForwardToNavigate',
	'restoreViewState',
	'centeredLayoutAutoResize',
	'limitEditorsEnablement',
	'limitEditorsMaximum',
	'perEditorGroup',
	'commandHistory',
	'preserveInput',
	'closeOnFocusLost',
	'workbench.quickOpen.preserveInput',
	'openDefaultSettings',
	'useSplitJSON',
	'openDefaultKeybindings',
	'sideBarLocation',
	'panelDefaultLocation',
	'panelOpensMaximized',
	'workbench.panel.opensMaximized.always',
	'workbench.panel.opensMaximized.never',
	'workbench.panel.opensMaximized.preserve',
	'statusBarVisibility',
	'activityBarVisibility',
	'activityBarIconClickBehavior',
	'workbench.activityBar.iconClickBehavior.toggle',
	'workbench.activityBar.iconClickBehavior.focus',
	'viewVisibility',
	'fontAliasing',
	'workbench.fontAliasing.default',
	'workbench.fontAliasing.antialiased',
	'workbench.fontAliasing.none',
	'workbench.fontAliasing.auto',
	'settings.editor.ui',
	'settings.editor.json',
	'settings.editor.desc',
	'workbench.hover.delay',
	'windowTitle',
	'activeEditorShort',
	'activeEditorMedium',
	'activeEditorLong',
	'activeFolderShort',
	'activeFolderMedium',
	'activeFolderLong',
	'folderName',
	'folderPath',
	'rootName',
	'rootPath',
	'appName',
	'remoteName',
	'dirty',
	'separator',
	'windowConfigurationTitle',
	"window.titleSeparator",
	'window.menuBarVisibility.classic',
	'window.menuBarVisibility.visible',
	'window.menuBarVisibility.toggle.mac',
	'window.menuBarVisibility.toggle',
	'window.menuBarVisibility.hidden',
	'window.menuBarVisibility.compact',
	'menuBarVisibility.mac',
	'menuBarVisibility',
	'enableMenuBarMnemonics',
	'customMenuBarAltFocus',
	'window.openFilesInNewWindow.on',
	'window.openFilesInNewWindow.off',
	'window.openFilesInNewWindow.defaultMac',
	'window.openFilesInNewWindow.default',
	'openFilesInNewWindowMac',
	'openFilesInNewWindow',
	'window.openFoldersInNewWindow.on',
	'window.openFoldersInNewWindow.off',
	'window.openFoldersInNewWindow.default',
	'openFoldersInNewWindow',
	'window.confirmBeforeClose.always',
	'window.confirmBeforeClose.keyboardOnly',
	'window.confirmBeforeClose.never',
	'confirmBeforeCloseWeb',
	'zenModeConfigurationTitle',
	'zenMode.fullScreen',
	'zenMode.centerLayout',
	'zenMode.hideTabs',
	'zenMode.hideStatusBar',
	'zenMode.hideActivityBar',
	'zenMode.hideLineNumbers',
	'zenMode.restore',
	'zenMode.silentNotifications',
	'workbench.experimental.useCustomHover'
]);