/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"The default size.",
	"Increases the size, so it can be grabbed more easily with the mouse.",
	"Controls the height of the scrollbars used for tabs and breadcrumbs in the editor title area.",
	"Controls whether opened editors should show in tabs or not.",
	"Controls whether tabs should be wrapped over multiple lines when exceeding available space or whether a scrollbar should appear instead. This value is ignored when `#workbench.editor.showTabs#` is disabled.",
	"Controls whether scrolling over tabs will open them or not. By default tabs will only reveal upon scrolling, but not open. You can press and hold the Shift-key while scrolling to change this behavior for that duration. This value is ignored when `#workbench.editor.showTabs#` is disabled.",
	"Controls whether a top border is drawn on modified (dirty) editor tabs or not. This value is ignored when `#workbench.editor.showTabs#` is disabled.",
	"Controls whether editor file decorations should use badges.",
	"Controls whether editor file decorations should use colors.",
	"Show the name of the file. When tabs are enabled and two files have the same name in one group the distinguishing sections of each file's path are added. When tabs are disabled, the path relative to the workspace folder is shown if the editor is active.",
	"Show the name of the file followed by its directory name.",
	"Show the name of the file followed by its path relative to the workspace folder.",
	"Show the name of the file followed by its absolute path.",
	"Controls the format of the label for an editor.",
	"The name of the untitled file is derived from the contents of its first line unless it has an associated file path. It will fallback to the name in case the line is empty or contains no word characters.",
	"The name of the untitled file is not derived from the contents of the file.",
	"Controls the format of the label for an untitled editor.",
	"Controls if the untitled hint should be inline text in the editor or a floating button or hidden.",
	"Controls the position of the editor's tabs close buttons, or disables them when set to 'off'. This value is ignored when `#workbench.editor.showTabs#` is disabled.",
	"Always keep tabs large enough to show the full editor label.",
	"Allow tabs to get smaller when the available space is not enough to show all tabs at once.",
	"Controls the sizing of editor tabs. This value is ignored when `#workbench.editor.showTabs#` is disabled.",
	"A pinned tab inherits the look of non pinned tabs.",
	"A pinned tab will show in a compact form with only icon or first letter of the editor name.",
	"A pinned tab shrinks to a compact fixed size showing parts of the editor name.",
	"Controls the sizing of pinned editor tabs. Pinned tabs are sorted to the beginning of all opened tabs and typically do not close until unpinned. This value is ignored when `#workbench.editor.showTabs#` is disabled.",
	"Splits all the editor groups to equal parts.",
	"Splits the active editor group to equal parts.",
	"Controls the sizing of editor groups when splitting them.",
	"Controls if editor groups can be split from drag and drop operations by dropping an editor or file on the edges of the editor area.",
	"Controls whether tabs are closed in most recently used order or from left to right.",
	"Controls whether opened editors should show with an icon or not. This requires a file icon theme to be enabled as well.",
	"Controls whether opened editors show as preview. Preview editors do not keep open and are reused until explicitly set to be kept open (e.g. via double click or editing) and show up with an italic font style.",
	"Controls whether editors opened from Quick Open show as preview. Preview editors do not keep open and are reused until explicitly set to be kept open (e.g. via double click or editing). This value is ignored when `#workbench.editor.enablePreview#` is disabled.",
	"Controls whether editors remain in preview when a code navigation is started from them. Preview editors do not keep open and are reused until explicitly set to be kept open (e.g. via double click or editing). This value is ignored when `#workbench.editor.enablePreview#` is disabled.",
	"Controls whether editors showing a file that was opened during the session should close automatically when getting deleted or renamed by some other process. Disabling this will keep the editor open  on such an event. Note that deleting from within the application will always close the editor and that dirty files will never close to preserve your data.",
	"Controls where editors open. Select `left` or `right` to open editors to the left or right of the currently active one. Select `first` or `last` to open editors independently from the currently active one.",
	"Controls the default direction of editors that are opened side by side (for example, from the Explorer). By default, editors will open on the right hand side of the currently active one. If changed to `down`, the editors will open below the currently active one.",
	"Controls the behavior of empty editor groups when the last tab in the group is closed. When enabled, empty groups will automatically close. When disabled, empty groups will remain part of the grid.",
	"Controls whether an editor is revealed in any of the visible groups if opened. If disabled, an editor will prefer to open in the currently active editor group. If enabled, an already opened editor will be revealed instead of opened again in the currently active editor group. Note that there are some cases where this setting is ignored, e.g. when forcing an editor to open in a specific group or to the side of the currently active group.",
	"Navigate between open files using mouse buttons four and five if provided.",
	"Restores the last view state (e.g. scroll position) when re-opening textual editors after they have been closed.",
	"Controls if the centered layout should automatically resize to maximum width when more than one group is open. Once only one group is open it will resize back to the original centered width.",
	"Controls if the number of opened editors should be limited or not. When enabled, less recently used editors that are not dirty will close to make space for newly opening editors.",
	"Controls the maximum number of opened editors. Use the `#workbench.editor.limit.perEditorGroup#` setting to control this limit per editor group or across all groups.",
	"Controls if the limit of maximum opened editors should apply per editor group or across all editor groups.",
	"Controls the number of recently used commands to keep in history for the command palette. Set to 0 to disable command history.",
	"Controls whether the last typed input to the command palette should be restored when opening it the next time.",
	"Controls whether Quick Open should close automatically once it loses focus.",
	"Controls whether the last typed input to Quick Open should be restored when opening it the next time.",
	"Controls whether opening settings also opens an editor showing all default settings.",
	"Controls whether to use the split JSON editor when editing settings as JSON.",
	"Controls whether opening keybinding settings also opens an editor showing all default keybindings.",
	"Controls the location of the sidebar and activity bar. They can either show on the left or right of the workbench.",
	"Controls the default location of the panel (terminal, debug console, output, problems). It can either show at the bottom, right, or left of the workbench.",
	"Controls whether the panel opens maximized. It can either always open maximized, never open maximized, or open to the last state it was in before being closed.",
	"Always maximize the panel when opening it.",
	"Never maximize the panel when opening it. The panel will open un-maximized.",
	"Open the panel to the state that it was in, before it was closed.",
	"Controls the visibility of the status bar at the bottom of the workbench.",
	"Controls the visibility of the activity bar in the workbench.",
	"Controls the behavior of clicking an activity bar icon in the workbench.",
	"Hide the side bar if the clicked item is already visible.",
	"Focus side bar if the clicked item is already visible.",
	"Controls the visibility of view header actions. View header actions may either be always visible, or only visible when that view is focused or hovered over.",
	"Controls font aliasing method in the workbench.",
	"Sub-pixel font smoothing. On most non-retina displays this will give the sharpest text.",
	"Smooth the font on the level of the pixel, as opposed to the subpixel. Can make the font appear lighter overall.",
	"Disables font smoothing. Text will show with jagged sharp edges.",
	"Applies `default` or `antialiased` automatically based on the DPI of displays.",
	"Use the settings UI editor.",
	"Use the JSON file editor.",
	"Determines which settings editor to use by default.",
	"Controls the delay in milliseconds after which the hover is shown for workbench items (ex. some extension provided tree view items). Already visible items may require a refresh before reflecting this setting change.",
	"Controls the window title based on the active editor. Variables are substituted based on the context:",
	"`\${activeEditorShort}`: the file name (e.g. myFile.txt).",
	"`\${activeEditorMedium}`: the path of the file relative to the workspace folder (e.g. myFolder/myFileFolder/myFile.txt).",
	"`\${activeEditorLong}`: the full path of the file (e.g. /Users/Development/myFolder/myFileFolder/myFile.txt).",
	"`\${activeFolderShort}`: the name of the folder the file is contained in (e.g. myFileFolder).",
	"`\${activeFolderMedium}`: the path of the folder the file is contained in, relative to the workspace folder (e.g. myFolder/myFileFolder).",
	"`\${activeFolderLong}`: the full path of the folder the file is contained in (e.g. /Users/Development/myFolder/myFileFolder).",
	"`\${folderName}`: name of the workspace folder the file is contained in (e.g. myFolder).",
	"`\${folderPath}`: file path of the workspace folder the file is contained in (e.g. /Users/Development/myFolder).",
	"`\${rootName}`: name of the opened workspace or folder (e.g. myFolder or myWorkspace).",
	"`\${rootPath}`: file path of the opened workspace or folder (e.g. /Users/Development/myWorkspace).",
	"`\${appName}`: e.g. VS Code.",
	"`\${remoteName}`: e.g. SSH",
	"`\${dirty}`: a dirty indicator if the active editor is dirty.",
	"`\${separator}`: a conditional separator (\" - \") that only shows when surrounded by variables with values or static text.",
	"Window",
	"Separator used by `window.title`.",
	"Menu is displayed at the top of the window and only hidden in full screen mode.",
	"Menu is always visible at the top of the window even in full screen mode.",
	"Menu is hidden but can be displayed at the top of the window by executing the `Focus Application Menu` command.",
	"Menu is hidden but can be displayed at the top of the window via the Alt key.",
	"Menu is always hidden.",
	"Menu is displayed as a compact button in the sidebar. This value is ignored when `#window.titleBarStyle#` is `native`.",
	"Control the visibility of the menu bar. A setting of 'toggle' means that the menu bar is hidden and executing `Focus Application Menu` will show it. A setting of 'compact' will move the menu into the sidebar.",
	"Control the visibility of the menu bar. A setting of 'toggle' means that the menu bar is hidden and a single press of the Alt key will show it. A setting of 'compact' will move the menu into the sidebar.",
	"Controls whether the main menus can be opened via Alt-key shortcuts. Disabling mnemonics allows to bind these Alt-key shortcuts to editor commands instead.",
	"Controls whether the menu bar will be focused by pressing the Alt-key. This setting has no effect on toggling the menu bar with the Alt-key.",
	"Files will open in a new window.",
	"Files will open in the window with the files' folder open or the last active window.",
	"Files will open in the window with the files' folder open or the last active window unless opened via the Dock or from Finder.",
	"Files will open in a new window unless picked from within the application (e.g. via the File menu).",
	"Controls whether files should open in a new window. \nNote that there can still be cases where this setting is ignored (e.g. when using the `--new-window` or `--reuse-window` command line option).",
	"Controls whether files should open in a new window.\nNote that there can still be cases where this setting is ignored (e.g. when using the `--new-window` or `--reuse-window` command line option).",
	"Folders will open in a new window.",
	"Folders will replace the last active window.",
	"Folders will open in a new window unless a folder is picked from within the application (e.g. via the File menu).",
	"Controls whether folders should open in a new window or replace the last active window.\nNote that there can still be cases where this setting is ignored (e.g. when using the `--new-window` or `--reuse-window` command line option).",
	"Always try to ask for confirmation. Note that browsers may still decide to close a tab or window without confirmation.",
	"Only ask for confirmation if a keybinding was detected. Note that detection may not be possible in some cases.",
	"Never explicitly ask for confirmation unless data loss is imminent.",
	"Controls whether to show a confirmation dialog before closing the browser tab or window. Note that even if enabled, browsers may still decide to close a tab or window without confirmation and that this setting is only a hint that may not work in all cases.",
	"Zen Mode",
	"Controls whether turning on Zen Mode also puts the workbench into full screen mode.",
	"Controls whether turning on Zen Mode also centers the layout.",
	"Controls whether turning on Zen Mode also hides workbench tabs.",
	"Controls whether turning on Zen Mode also hides the status bar at the bottom of the workbench.",
	"Controls whether turning on Zen Mode also hides the activity bar either at the left or right of the workbench.",
	"Controls whether turning on Zen Mode also hides the editor line numbers.",
	"Controls whether a window should restore to zen mode if it was exited in zen mode.",
	"Controls whether notifications are shown while in zen mode. If true, only error notifications will pop out.",
	"Enable/disable custom hovers on Activity Bar & Panel. Note this configuration is experimental and subjected to be removed at any time."
]);