/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Notebook",
	"Execute Cell",
	"Execute Cell",
	"Stop Cell Execution",
	"Stop Cell Execution",
	"Delete Cell",
	"Execute Notebook Cell and Select Below",
	"Execute Notebook Cell and Insert Below",
	"Render All Markdown Cells",
	"Execute Notebook (Run all cells)",
	"Execute Notebook (Run all cells)",
	"Stop Notebook Execution",
	"Stop Notebook Execution",
	"Insert Cell",
	"Notebook Cell",
	"Change Cell to Code",
	"Change Cell to Markdown",
	"Insert Code Cell Above",
	"Insert Code Cell Below",
	"Add Code Cell At Top",
	"Add Markdown Cell At Top",
	"$(add) Code",
	"Add Code Cell",
	"$(add) Code",
	"Add Code Cell",
	"Insert Markdown Cell Above",
	"Insert Markdown Cell Below",
	"$(add) Markdown",
	"Add Markdown Cell",
	"$(add) Markdown",
	"Add Markdown Cell",
	"Edit Cell",
	"Stop Editing Cell",
	"Delete Cell",
	'Clear Cell Outputs',
	'Change Cell Language',
	'Change Cell Language',
	"({0}) - Current Language",
	"({0})",
	"Select Language Mode",
	'Clear All Cells Outputs',
	"Center Active Cell",
	"Collapse Cell Input",
	"Expand Cell Input",
	"Collapse Cell Output",
	"Expand Cell Output"
]);