/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'defaultPreferencesEditor',
	'settingsEditor2',
	'keybindingsEditor',
	'openSettings2',
	'preferences',
	'settings',
	{ key: 'miOpenSettings', comment: ['&& denotes a mnemonic'] },
	'openSettings2',
	'openSettingsJson',
	'openGlobalSettings',
	'openRawDefaultSettings',
	'openSettingsJson',
	'openWorkspaceSettings',
	'openWorkspaceSettingsFile',
	'openFolderSettings',
	'openFolderSettingsFile',
	'openFolderSettings',
	'filterModifiedLabel',
	'filterOnlineServicesLabel',
	{ key: 'miOpenOnlineSettings', comment: ['&& denotes a mnemonic'] },
	'onlineServices',
	'filterUntrusted',
	'openRemoteSettings',
	'settings.focusSearch',
	'settings.clearResults',
	'settings.focusFile',
	'settings.focusFile',
	'settings.focusNextSetting',
	'settings.focusPreviousSetting',
	'settings.editFocusedSetting',
	'settings.focusSettingsList',
	'settings.focusSettingsTOC',
	'settings.focusSettingControl',
	'settings.showContextMenu',
	'settings.focusLevelUp',
	'preferences',
	'openGlobalKeybindings',
	'Keyboard Shortcuts',
	'Keyboard Shortcuts',
	'openDefaultKeybindingsFile',
	'openGlobalKeybindingsFile',
	'showDefaultKeybindings',
	'showExtensionKeybindings',
	'showUserKeybindings',
	'clear',
	{ key: 'miPreferences', comment: ['&& denotes a mnemonic'] }
]);