/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Default Preferences Editor",
	"Settings Editor 2",
	"Keybindings Editor",
	"Open Settings (UI)",
	"Preferences",
	"Settings",
	"&&Settings",
	"Open Settings (UI)",
	"Open Settings (JSON)",
	"Open User Settings",
	"Open Default Settings (JSON)",
	"Open Settings (JSON)",
	"Open Workspace Settings",
	"Open Workspace Settings (JSON)",
	"Open Folder Settings",
	"Open Folder Settings (JSON)",
	"Open Folder Settings",
	"Show modified settings",
	"Show settings for online services",
	"&&Online Services Settings",
	"Online Services Settings",
	"Show untrusted workspace settings",
	"Open Remote Settings ({0})",
	"Focus Settings Search",
	"Clear Settings Search Results",
	"Focus settings file",
	"Focus settings file",
	"Focus next setting",
	"Focus previous setting",
	"Edit focused setting",
	"Focus settings list",
	"Focus Settings Table of Contents",
	"Focus Setting Control",
	"Show Setting Context Menu",
	"Move Focus Up One Level",
	"Preferences",
	"Open Keyboard Shortcuts",
	"Keyboard Shortcuts",
	"Keyboard Shortcuts",
	"Open Default Keyboard Shortcuts (JSON)",
	"Open Keyboard Shortcuts (JSON)",
	"Show Default Keybindings",
	"Show Extension Keybindings",
	"Show User Keybindings",
	"Clear Search Results",
	"&&Preferences"
]);