/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"The foreground color for a section header or active title.",
	"The color of the modified setting indicator.",
	"Settings editor dropdown background.",
	"Settings editor dropdown foreground.",
	"Settings editor dropdown border.",
	"Settings editor dropdown list border. This surrounds the options and separates the options from the description.",
	"Settings editor checkbox background.",
	"Settings editor checkbox foreground.",
	"Settings editor checkbox border.",
	"Settings editor text input box background.",
	"Settings editor text input box foreground.",
	"Settings editor text input box border.",
	"Settings editor number input box background.",
	"Settings editor number input box foreground.",
	"Settings editor number input box border.",
	"The background color of a settings row when focused.",
	"The background color of a settings row when hovered.",
	"The color of the row's top and bottom border when the row is focused.",
	"OK",
	"Cancel",
	"List item `{0}`",
	"List item `{0}` with sibling `${1}`",
	"Remove Item",
	"Edit Item",
	"Add Item",
	"String Item...",
	"Sibling...",
	"Exclude files matching `{0}`",
	"Exclude files matching `{0}`, only when a file matching `{1}` is present",
	"Remove Exclude Item",
	"Edit Exclude Item",
	"Add Pattern",
	"Exclude Pattern...",
	"When Pattern Is Present...",
	"OK",
	"Cancel",
	"Key",
	"Value",
	"The property `{0}` is set to `{1}`.",
	"Remove Item",
	"Reset Item",
	"Edit Item",
	"Add Item",
	"Item",
	"Value"
]);