/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Commonly Used",
	"Text Editor",
	"Cursor",
	"Find",
	"Font",
	"Formatting",
	"Diff Editor",
	"Minimap",
	"Suggestions",
	"Files",
	"Workbench",
	"Appearance",
	"Breadcrumbs",
	"Editor Management",
	"Settings Editor",
	"Zen Mode",
	"Screencast Mode",
	"Window",
	"New Window",
	"Features",
	"Explorer",
	"Search",
	"Debug",
	"Testing",
	"SCM",
	"Extensions",
	"Terminal",
	"Task",
	"Problems",
	"Output",
	"Comments",
	"Remote",
	"Timeline",
	'Notebook',
	"Application",
	"Proxy",
	"Keyboard",
	"Update",
	"Telemetry",
	"Settings Sync",
	"Security",
	"Workspace"
]);