/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"{0} ({1})",
	"1 problem in this element",
	"{0} problems in this element",
	"Contains elements with problems",
	"array",
	"boolean",
	"class",
	"constant",
	"constructor",
	"enumeration",
	"enumeration member",
	"event",
	"field",
	"file",
	"function",
	"interface",
	"key",
	"method",
	"module",
	"namespace",
	"null",
	"number",
	"object",
	"operator",
	"package",
	"property",
	"string",
	"struct",
	"type parameter",
	"variable"
]);