/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'lineHighlight',
	'lineHighlightBorderBox',
	'rangeHighlight',
	'rangeHighlightBorder',
	'symbolHighlight',
	'symbolHighlightBorder',
	'caret',
	'editorCursorBackground',
	'editorWhitespaces',
	'editorIndentGuides',
	'editorActiveIndentGuide',
	'editorLineNumbers',
	'editorActiveLineNumber',
	'deprecatedEditorActiveLineNumber',
	'editorActiveLineNumber',
	'editorRuler',
	'editorCodeLensForeground',
	'editorBracketMatchBackground',
	'editorBracketMatchBorder',
	'editorOverviewRulerBorder',
	'editorOverviewRulerBackground',
	'editorGutter',
	'unnecessaryCodeBorder',
	'unnecessaryCodeOpacity',
	'overviewRulerRangeHighlight',
	'overviewRuleError',
	'overviewRuleWarning',
	'overviewRuleInfo'
]);