/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Icon used for the setup category of getting started",
	"Icon used for the beginner category of getting started",
	"Icon used for the intermediate category of getting started",
	"Icon used for the codespaces category of getting started",
	"New File",
	"Start with a new empty file",
	"Open...",
	"Open a file or folder to start working",
	"Open File...",
	"Open a file to start working",
	"Open Folder...",
	"Open a folder to start working",
	"Clone Git Repository...",
	"Clone a git repository",
	"Run a Command...",
	"Use the command palette to view and run all of vscode's commands",
	"Primer on Codespaces",
	"Get up and running with your instant code environment.",
	"Build & run your app",
	"Build, run & debug your code in the cloud, right from the browser.\n[Start Debugging](command:workbench.action.debug.selectandstart)",
	"Access your running application",
	"Ports running within your codespace are automatically forwarded to the web, so you can open them in your browser.\n[Show Ports Panel](command:~remote.forwardedPorts.focus)",
	"Pull requests at your fingertips",
	"Bring your GitHub workflow closer to your code, so you can review pull requests, add comments, merge branches, and more.\n[Open GitHub View](command:workbench.view.extension.github-pull-requests)",
	"Run tasks in the integrated terminal",
	"Perform quick command-line tasks using the built-in terminal.\n[Focus Terminal](command:terminal.focus)",
	"Develop remotely in VS Code",
	"Access the power of your cloud development environment from your local VS Code. Set it up by installing the GitHub Codespaces extension and connecting your GitHub account.\n[Open in VS Code](command:github.codespaces.openInStable)",
	"Customize your Setup",
	"Extend and customize VS Code to make it yours.",
	"Customize the look with themes",
	"Pick a color theme to match your taste and mood while coding.\n[Pick a Theme](command:workbench.action.selectTheme)",
	"Code in any language",
	"VS Code supports over 50+ programming languages. While many are built-in, others can be easily installed as extensions in one click.\n[Browse Language Extensions](command:workbench.extensions.action.showLanguageExtensions)",
	"Switch from other editors",
	"Bring your favorite keyboard shortcuts from other editors into VS Code with keymaps.\n[Browse Keymap Extensions](command:workbench.extensions.action.showRecommendedKeymapExtensions)",
	"Sync your favorite setup",
	"Never lose the perfect VS Code setup! Settings Sync will back up and share settings, keybindings & extensions across several VS Code instances.\n[Enable Settings Sync](command:workbench.userDataSync.actions.turnOn)",
	"Open your project folder",
	"Open a project folder to start coding!\n[Pick a Folder](command:workbench.action.files.openFileFolder)",
	"Open your project folder",
	"Open a project folder to start coding!\n[Pick a Folder](command:workbench.action.files.openFolder)",
	"Quick open files",
	"Navigate between files in an instant with one keystroke. Tip: Open multiple files by pressing the right arrow key.\n[Quick Open a File](command:toSide:workbench.action.quickOpen)",
	"Learn the Fundamentals",
	"Jump right into VS Code and get an overview of the must-have features.",
	"Find & run commands",
	"The easiest way to find everything VS Code can do. If you're ever looking for a feature or a shortcut, check here first!\n[Open Command Palette](command:workbench.action.showCommands)",
	"Convenient built-in terminal",
	"Quickly run shell commands and monitor build output, right next to your code.\n[Show Terminal Panel](command:workbench.action.terminal.toggleTerminal)",
	"Limitless extensibility",
	"Extensions are VS Code's power-ups. They range from handy productivity hacks, expanding out-of-the-box features, to adding completely new capabilities.\n[Browse Recommended Extensions](command:workbench.extensions.action.showRecommendedExtensions)",
	"Tune your settings",
	"Tweak every aspect of VS Code and your extensions to your liking. Commonly used settings are listed first to get you started.\n[Tweak my Settings](command:toSide:workbench.action.openSettings)",
	"Lean back and learn",
	"Watch the first in a series of short & practical video tutorials for VS Code's key features.\n[Watch Tutorial](https://aka.ms/vscode-getting-started-video)",
	"Boost your Productivity",
	"Optimize your development workflow with these tips & tricks.",
	"Redefine your editing skills",
	"Want to code faster and smarter? Practice powerful code editing features in the interactive playground.\n[Open Interactive Playground](command:toSide:workbench.action.showInteractivePlayground)",
	"Side by side editing",
	"Make the most of your screen estate by opening files side by side, vertically and horizontally.\n[Split Editor](command:workbench.action.splitEditor)",
	"Watch your code in action",
	"Accelerate your edit, build, test, and debug loop by setting up a launch configuration.\n[Run your Project](command:workbench.action.debug.selectandstart)",
	"Track your code with Git",
	"Set up the built-in version control for your project to track your changes and collaborate with others.\n[Clone Repository](command:git.clone)",
	"Track your code with Git",
	"Set up the built-in version control for your project to track your changes and collaborate with others.\n[Initialize Git Repository](command:git.init)",
	"Track your code with Git",
	"No more looking up Git commands! Git and GitHub workflows are seamlessly integrated.[Open Source Control](command:workbench.view.scm)",
	"Automate your project tasks",
	"Create tasks for your common workflows and enjoy the integrated experience of running scripts and automatically checking results.\n[Run Auto-detected Tasks](command:workbench.action.tasks.runTask)",
	"Customize your shortcuts",
	"Once you have discovered your favorite commands, create custom keyboard shortcuts for instant access.\n[Keyboard Shortcuts](command:toSide:workbench.action.openGlobalKeybindings)"
]);