/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'contributes.notebook.provider',
	'contributes.notebook.provider.viewType',
	'contributes.notebook.provider.displayName',
	'contributes.notebook.provider.selector',
	'contributes.notebook.provider.selector.filenamePattern',
	'contributes.notebook.selector.provider.excludeFileNamePattern',
	'contributes.priority',
	'contributes.priority.default',
	'contributes.priority.option',
	'contributes.notebook.renderer',
	'contributes.notebook.renderer.viewType',
	'contributes.notebook.provider.viewType.deprecated',
	'contributes.notebook.renderer.viewType',
	'contributes.notebook.renderer.displayName',
	'contributes.notebook.selector',
	'contributes.notebook.renderer.entrypoint',
	'contributes.notebook.renderer.hardDependencies',
	'contributes.notebook.renderer.optionalDependencies',
	'contributes.notebook.markdownRenderer',
	'contributes.notebook.markdownRenderer.id',
	'contributes.notebook.markdownRenderer.displayName',
	'contributes.notebook.markdownRenderer.entrypoint',
	'contributes.notebook.markdownRenderer.mimeTypes',
	'contributes.notebook.markdownRenderer.dependsOn'
]);