/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Debug",
	"Type the name of a launch configuration to run.",
	"Start Debugging",
	"Terminate Thread",
	'Focus on Debug Console View',
	"Jump to Cursor",
	"Set Next Statement",
	"Inline Breakpoint",
	"Terminate Thread",
	"Restart Frame",
	"Copy Call Stack",
	"Set Value",
	"Copy Value",
	"Copy as Expression",
	"Add to Watch",
	"Break on Value Read",
	"Break on Value Change",
	"Break on Value Access",
	"Edit Expression",
	"Copy Value",
	"Remove Expression",
	"&&Start Debugging",
	"Run &&Without Debugging",
	"&&Stop Debugging",
	"&&Restart Debugging",
	"A&&dd Configuration...",
	"Step &&Over",
	"Step &&Into",
	"Step O&&ut",
	"&&Continue",
	"Inline Breakp&&oint",
	"&&New Breakpoint",
	"&&Install Additional Debuggers...",
	'Debug Console',
	'Debug Console',
	"De&&bug Console",
	"Run and Debug",
	"&&Run",
	"Variables",
	"Watch",
	"Call Stack",
	"Breakpoints",
	"Loaded Scripts",
	"Debug",
	"Allow setting breakpoints in any file.",
	"Automatically open the explorer view at the end of a debug session.",
	"Show variable values inline in editor while debugging.",
	'Always show variable values inline in editor while debugging.',
	'Never show variable values inline in editor while debugging.',
	'Show variable values inline in editor while debugging when the language supports inline value locations.',
	"Controls the location of the debug toolbar. Either `floating` in all views, `docked` in the debug view, or `hidden`.",
	"Never show debug in status bar",
	"Always show debug in status bar",
	"Show debug in status bar only after debug was started for the first time",
	"Controls when the debug status bar should be visible.",
	"Controls if the debug console should be automatically closed when the debug session ends.",
	"Before starting a new debug session in an integrated or external terminal, clear the terminal.",
	"Controls when the debug view should open.",
	"Controls whether the debug sub-sessions are shown in the debug tool bar. When this setting is false the stop command on a sub-session will also stop the parent session.",
	"Controls the font size in pixels in the debug console.",
	"Controls the font family in the debug console.",
	"Controls the line height in pixels in the debug console. Use 0 to compute the line height from the font size.",
	"Controls if the lines should wrap in the debug console.",
	"Controls if the debug console should suggest previously typed input.",
	"Controls if the debug console should collapse identical lines and show a number of occurrences with a badge.",
	"Global debug launch configuration. Should be used as an alternative to 'launch.json' that is shared across workspaces.",
	"Controls whether the workbench window should be focused when the debugger breaks.",
	"Ignore task errors and start debugging.",
	"Show the Problems view and do not start debugging.",
	"Prompt user.",
	"Cancel debugging.",
	"Controls what to do when errors are encountered after running a preLaunchTask.",
	"Controls whether breakpoints should be shown in the overview ruler.",
	"Controls whether inline breakpoints candidate decorations should be shown in the editor while debugging.",
	"Controls what editors to save before starting a debug session.",
	"Save all editors in the active group before starting a debug session.",
	"Save all editors in the active group except untitled ones before starting a debug session.",
	"Don't save any editors before starting a debug session."
]);