/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'contributes.icons',
	'contributes.icon.id',
	'contributes.icon.id.format',
	'contributes.icon.description',
	'contributes.icon.default.fontId',
	'contributes.icon.default.fontCharacter',
	'contributes.icon.default',
	'contributes.iconFonts',
	'contributes.iconFonts.id',
	'contributes.iconFonts.id.formatError',
	'contributes.iconFonts.src',
	'contributes.iconFonts.src.path',
	'contributes.iconFonts.src.format',
	'invalid.icons.proposedAPI',
	'invalid.icons.configuration',
	'invalid.icons.id',
	'invalid.icons.id.format',
	'invalid.icons.description',
	'invalid.icons.default',
	'invalid.iconFonts.proposedAPI',
	'invalid.iconFonts.configuration',
	'invalid.iconFonts.id',
	'invalid.iconFonts.id.format',
	'invalid.iconFonts.src',
	'invalid.iconFonts.src.path',
	'invalid.iconFonts.src.item'
]);