/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'colorTheme',
	'colorThemeError',
	{ key: 'preferredDarkColorTheme', comment: ['`#{0}#` will become a link to an other setting. Do not remove backtick or #'] },
	'colorThemeError',
	{ key: 'preferredLightColorTheme', comment: ['`#{0}#` will become a link to an other setting. Do not remove backtick or #'] },
	'colorThemeError',
	{ key: 'preferredHCColorTheme', comment: ['`#{0}#` will become a link to an other setting. Do not remove backtick or #'] },
	'colorThemeError',
	'detectColorScheme',
	'workbenchColors',
	'iconTheme',
	'noIconThemeLabel',
	'noIconThemeDesc',
	'iconThemeError',
	'productIconTheme',
	'defaultProductIconThemeLabel',
	'defaultProductIconThemeDesc',
	'productIconThemeError',
	'autoDetectHighContrast',
	'editorColors.comments',
	'editorColors.strings',
	'editorColors.keywords',
	'editorColors.numbers',
	'editorColors.types',
	'editorColors.functions',
	'editorColors.variables',
	'editorColors.textMateRules',
	'editorColors.semanticHighlighting',
	'editorColors.semanticHighlighting.deprecationMessage',
	'editorColors.semanticHighlighting.deprecationMessageMarkdown',
	'editorColors',
	'editorColors.semanticHighlighting.enabled',
	'editorColors.semanticHighlighting.rules',
	'semanticTokenColors',
	'editorColors.experimentalTokenStyling.deprecationMessage',
	'editorColors.experimentalTokenStyling.deprecationMessageMarkdown'
]);