/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"{0} years ago",
	"1 year ago",
	"{0} months ago",
	"1 month ago",
	"{0} days ago",
	"1 day ago",
	"{0} hours ago",
	"1 hour ago",
	"Just now",
	"VS Code Web",
	"The '{0}' extension is not available in {1}. Click 'More Information' to learn more.",
	"Close",
	"More Information",
	"Try Downloading Manually...",
	'Once downloaded, please manually install the downloaded VSIX of \'{0}\'.',
	"Install from VSIX...",
	"Error while updating '{0}' extension.",
	"Error while installing '{0}' extension.",
	"Please check the [log]({0}) for more details.",
	"Installing extension {0} started. An editor is now open with more details on this extension",
	"Installing extension {0} is completed.",
	"Install",
	"Install (Do not sync)",
	"Install",
	"Install in {0} (Do not sync)",
	"Install in {0}",
	"Install Locally (Do not sync)",
	"Install Locally",
	"Install",
	"Install this extension in all your synced {0} instances",
	"Installing",
	"Install",
	"Installing",
	"Installing extension {0} started. An editor is now open with more details on this extension",
	"Install in {0}",
	"Install Locally",
	"Install in Browser",
	"Uninstall",
	"Uninstalling",
	"Uninstalling extension {0} started.",
	"Please reload Visual Studio Code to complete the uninstallation of the extension {0}.",
	"Updating extension {0} to version {1} started.",
	"Updating extension {0} to version {1} completed.",
	"Update to {0}",
	"Update",
	"Manage",
	"Uninstalling",
	"Manage",
	"Install Another Version...",
	"Select Version to Install",
	"Current",
	"Enable (Workspace)",
	"Enable this extension only in this workspace",
	"Enable",
	"Enable this extension",
	"Disable (Workspace)",
	"Disable this extension only in this workspace",
	"Disable",
	"Disable this extension",
	"Enable",
	"Disable",
	"Reload",
	"Reload Required",
	"Please reload Visual Studio Code to complete the uninstallation of this extension.",
	"Please reload Visual Studio Code to complete the uninstallation of the extension {0}.",
	"Reload Required",
	"Please reload Visual Studio Code to enable the updated extension.",
	"Reload Required",
	"Please reload Visual Studio Code to enable this extension locally.",
	"Reload Required",
	"Please reload Visual Studio Code to enable this extension in {0}.",
	"Reload Required",
	"Please reload Visual Studio Code to enable this extension.",
	"Reload Required",
	"Please reload Visual Studio Code to enable this extension.",
	"Reload Required",
	"Please reload Visual Studio Code to disable this extension.",
	"Reload Required",
	"Please reload Visual Studio Code to enable this extension.",
	"Reload Required",
	"Please reload Visual Studio Code to enable this extension.",
	"Installing extension {0} is completed. Please reload Visual Studio Code to enable it.",
	"Current",
	"Set Color Theme",
	"Select Color Theme",
	"Set File Icon Theme",
	"Select File Icon Theme",
	"Set Product Icon Theme",
	"Select Product Icon Theme",
	"Show Recommended Extension",
	"Install Recommended Extension",
	"Do not recommend this extension again",
	"Undo",
	"Search Extensions",
	"Unable to create 'extensions.json' file inside the '.vscode' folder ({0}).",
	"Configure Recommended Extensions (Workspace)",
	"Configure Recommended Extensions (Workspace Folder)",
	"Updated",
	"Installed",
	"Uninstalled",
	"Enabled",
	"Disabled",
	"This extension was reported to be problematic.",
	"Malicious",
	"This extension was reported to be problematic.",
	"This extension is ignored during sync",
	"This extension is synced",
	"Sync this extension",
	"Do not sync this extension",
	"Extension is enabled on '{0}'",
	"This extension is enabled globally.",
	"This extension is enabled for this workspace by the user.",
	"This extension is disabled globally by the user.",
	"This extension is disabled for this workspace by the user.",
	"This extension has been disabled because it does not support virtual workspaces.",
	"Install the language pack extension on '{0}' to enable it there also.",
	"Install the language pack extension locally to enable it there also.",
	"Install the extension on '{0}' to enable.",
	"This extension has defined that it cannot run on the remote server",
	"Extension is enabled on '{0}' and disabled locally.",
	"Extension is enabled locally and disabled on '{0}'.",
	"This extension has been disabled because the current workspace is not trusted",
	"Reinstall Extension...",
	"Select Extension to Reinstall",
	"Please reload Visual Studio Code to complete reinstalling the extension {0}.",
	"Reinstalling the extension {0} is completed.",
	"Reload Now",
	"Install Specific Version of Extension...",
	"Select Extension",
	"Current",
	"Select Version to Install",
	"Please reload Visual Studio Code to complete installing the extension {0}.",
	"Installing the extension {0} is completed.",
	"Reload Now",
	"Select extensions to install",
	"There are no extensions to install.",
	"Installing Extensions...",
	"Successfully installed extensions.",
	"Install Local Extensions in '{0}'...",
	"Install Local Extensions in '{0}'",
	"Install Remote Extensions Locally...",
	"Install Remote Extensions Locally",
	"Button background color for actions extension that stand out (e.g. install button).",
	"Button foreground color for actions extension that stand out (e.g. install button).",
	"Button background hover color for actions extension that stand out (e.g. install button)."
]);