/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Press Enter to manage extensions.",
	"Manage Extensions",
	"Extension",
	"Extensions",
	"E&&xtensions",
	"Extensions",
	"All Extensions",
	"Only Enabled Extensions",
	"None",
	'Download and install updates automatically for all extensions.',
	'Download and install updates automatically only for enabled extensions. Disabled extensions will not be updated automatically.',
	'Extensions are not automatically updated.',
	"Controls the automatic update behavior of extensions. The updates are fetched from a Microsoft online service.",
	"When enabled, automatically checks extensions for updates. If an extension has an update, it is marked as outdated in the Extensions view. The updates are fetched from a Microsoft online service.",
	"When enabled, the notifications for extension recommendations will not be shown.",
	"This setting is deprecated. Use extensions.ignoreRecommendations setting to control recommendation notifications. Use Extensions view's visibility actions to hide Recommended view by default.",
	"When enabled, editors with extension details will be automatically closed upon navigating away from the Extensions View.",
	"When an extension is listed here, a confirmation prompt will not be shown when that extension handles a URI.",
	"Enable web worker extension host.",
	"Override the virtual workspaces support of an extension.",
	"Override the untrusted workpace support of an extension. Extensions using `true` will always be enabled. Extensions using `limited` will always be enabled, and the extension will hide functionality that requires trust. Extensions using `false` will only be enabled only when the workspace is trusted.",
	"Extension will always be enabled.",
	"Extension will only be enabled only when the workspace is trusted.",
	"Extension will always be enabled, and the extension will hide functionality requiring trust.",
	"Defines the untrusted workspace support setting for the extension.",
	"Defines the version of the extension for which the override should be applied. If not specified, the override will be applied independent of the extension version.",
	"Install the given extension",
	"Extension id or VSIX resource uri",
	"Extension '{0}' not found.",
	"Uninstall the given extension",
	"Id of the extension to uninstall",
	"Extension id required.",
	"Extension '{0}' is not installed. Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp.",
	"Extension '{0}' is a Built-in extension and cannot be installed",
	"Search for a specific extension",
	"Query to use in search",
	"Type the name of an extension to install or search.",
	"Install or Search Extensions",
	"&&Extensions",
	"Extensions",
	"Install Extensions",
	"Keymaps",
	"&&Keymaps",
	"Keymaps",
	"Language Extensions",
	"Check for Extension Updates",
	"All extensions are up to date.",
	"Auto Update Extensions",
	"All Extensions",
	"Only Enabled Extensions",
	"None",
	"Update All Extensions",
	"Disable Auto Update for all extensions",
	"Enable Auto Update for all extensions",
	"Enable All Extensions",
	"Enable All Extensions for this Workspace",
	"Disable All Installed Extensions",
	"Disable All Installed Extensions for this Workspace",
	"Install from VSIX...",
	"Install from VSIX",
	"&&Install",
	"Install Extension VSIX",
	"Completed installing {0} extension from VSIX. Please reload Visual Studio Code to enable it.",
	"Completed installing {0} extension from VSIX.",
	"Reload Now",
	"Filter Extensions...",
	"Show Featured Extensions",
	"Featured",
	"Show Popular Extensions",
	"Most Popular",
	"Show Recommended Extensions",
	"Recommended",
	"Show Recently Published Extensions",
	"Recently Published",
	"Category",
	"Show Built-in Extensions",
	"Built-in",
	"Show Extensions Requiring Trust",
	"Show Installed Extensions",
	"Installed",
	"Show Enabled Extensions",
	"Enabled",
	"Show Disabled Extensions",
	"Disabled",
	"Show Outdated Extensions",
	"Outdated",
	"Sort By",
	"Install Count",
	"Rating",
	"Name",
	"Published Date",
	"Clear Extensions Search Results",
	"Refresh",
	"Install Workspace Recommended Extensions",
	"Copy",
	'Name: {0}',
	'Id: {0}',
	'Description: {0}',
	'Version: {0}',
	'Publisher: {0}',
	'VS Marketplace Link: {0}',
	"Copy Extension Id",
	"Extension Settings",
	"Sync This Extension",
	"Ignore Recommendation",
	"Undo Ignored Recommendation",
	"Add to Workspace Recommendations",
	"Remove from Workspace Recommendations",
	"Add Extension to Workspace Recommendations",
	"Extensions",
	"Add Extension to Workspace Folder Recommendations",
	"Extensions",
	"Add Extension to Workspace Ignored Recommendations",
	"Extensions",
	"Add Extension to Workspace Folder Ignored Recommendations",
	"Extensions",
	"Extensions"
]);