/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'name',
	'extension id',
	'preview',
	'preview',
	'builtin',
	'publisher',
	'install count',
	'rating',
	'repository',
	'license',
	'version',
	'details',
	'detailstooltip',
	'contributions',
	'contributionstooltip',
	'changelog',
	'changelogtooltip',
	'dependencies',
	'dependenciestooltip',
	'extensionpack',
	'extensionpacktooltip',
	'recommendationHasBeenIgnored',
	'noReadme',
	'extension pack',
	'noReadme',
	'noChangelog',
	'noContributions',
	'noContributions',
	'noDependencies',
	'noextensions',
	'settings',
	'setting name',
	'description',
	'default',
	'debuggers',
	'debugger name',
	'debugger type',
	'viewContainers',
	'view container id',
	'view container title',
	'view container location',
	'views',
	'view id',
	'view name',
	'view location',
	'localizations',
	'localizations language id',
	'localizations language name',
	'localizations localized language name',
	'customEditors',
	'customEditors view type',
	'customEditors priority',
	'customEditors filenamePattern',
	'codeActions',
	'codeActions.title',
	'codeActions.kind',
	'codeActions.description',
	'codeActions.languages',
	'authentication',
	'authentication.label',
	'authentication.id',
	'colorThemes',
	'iconThemes',
	'productThemes',
	'colors',
	'colorId',
	'description',
	'defaultDark',
	'defaultLight',
	'defaultHC',
	'JSON Validation',
	'fileMatch',
	'schema',
	'commands',
	'command name',
	'description',
	'keyboard shortcuts',
	'menuContexts',
	'languages',
	'language id',
	'language name',
	'file extensions',
	'grammar',
	'snippets',
	'activation events',
	'find',
	'find next',
	'find previous'
]);