/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'installed',
	'select and install local extensions',
	{ key: 'remote', comment: ['Remote as in remote machine'] },
	'install remote in local',
	{ key: 'remote', comment: ['Remote as in remote machine'] },
	'popularExtensions',
	'recommendedExtensions',
	'enabledExtensions',
	'disabledExtensions',
	'marketPlace',
	'installed',
	'enabled',
	'disabled',
	'outdated',
	'builtin',
	'trustRequired',
	'workspaceRecommendedExtensions',
	'otherRecommendedExtensions',
	'builtinFeatureExtensions',
	'builtInThemesExtensions',
	'builtinProgrammingLanguageExtensions',
	'trustRequiredOnStartExtensions',
	'trustRequiredOnDemandExtensions',
	'searchExtensions',
	'extensionFoundInSection',
	'extensionFound',
	'extensionsFoundInSection',
	'extensionsFound',
	'suggestProxyError',
	'open user settings',
	'outdatedExtensions',
	'malicious warning',
	'reloadNow'
]);