/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Installed",
	"Install Local Extensions in '{0}'...",
	"Remote",
	"Install Remote Extensions Locally...",
	"Remote",
	"Popular",
	"Recommended",
	"Enabled",
	"Disabled",
	"Marketplace",
	"Installed",
	"Enabled",
	"Disabled",
	"Outdated",
	"Builtin",
	"Trust Required",
	"Workspace Recommendations",
	"Other Recommendations",
	"Features",
	"Themes",
	"Programming Languages",
	"Trust Required To Enable",
	"Trust Required For Features",
	"Search Extensions in Marketplace",
	"1 extension found in the {0} section.",
	"1 extension found.",
	"{0} extensions found in the {1} section.",
	"{0} extensions found.",
	"Marketplace returned 'ECONNREFUSED'. Please check the 'http.proxy' setting.",
	"Open User Settings",
	'{0} Outdated Extensions',
	"We have uninstalled '{0}' which was reported to be problematic.",
	"Reload Now"
]);