/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'noOfYearsAgo',
	'one year ago',
	'noOfMonthsAgo',
	'one month ago',
	'noOfDaysAgo',
	'one day ago',
	'noOfHoursAgo',
	'one hour ago',
	'just now',
	{ key: 'vscode web', comment: ['VS Code Web is the name of the product'] },
	'cannot be installed',
	'close',
	'more information',
	'download',
	'install vsix',
	'installVSIX',
	'update operation',
	'install operation',
	'check logs',
	'installExtensionStart',
	'installExtensionComplete',
	'install',
	'install and do no sync',
	'install',
	{ key: 'install in remote and do not sync', comment: ['This is the name of the action to install an extension in remote server and do not sync it. Placeholder is for the name of remote server.'] },
	{ key: 'install in remote', comment: ['This is the name of the action to install an extension in remote server. Placeholder is for the name of remote server.'] },
	'install locally and do not sync',
	'install locally',
	'install',
	{ key: 'install everywhere tooltip', comment: ['Placeholder is the name of the product. Eg: Visual Studio Code or Visual Studio Code - Insiders'] },
	'installing',
	'install',
	'installing',
	'installExtensionStart',
	{ key: 'install in remote', comment: ['This is the name of the action to install an extension in remote server. Placeholder is for the name of remote server.'] },
	'install locally',
	'install browser',
	'uninstallAction',
	'Uninstalling',
	'uninstallExtensionStart',
	'uninstallExtensionComplete',
	'updateExtensionStart',
	'updateExtensionComplete',
	'updateTo',
	'updateAction',
	'manage',
	'ManageExtensionAction.uninstallingTooltip',
	'manage',
	'install another version',
	'selectVersion',
	'current',
	'enableForWorkspaceAction',
	'enableForWorkspaceActionToolTip',
	'enableGloballyAction',
	'enableGloballyActionToolTip',
	'disableForWorkspaceAction',
	'disableForWorkspaceActionToolTip',
	'disableGloballyAction',
	'disableGloballyActionToolTip',
	'enableAction',
	'disableAction',
	'reloadAction',
	'reloadRequired',
	'postUninstallTooltip',
	'uninstallExtensionComplete',
	'reloadRequired',
	'postUpdateTooltip',
	'reloadRequired',
	'enable locally',
	'reloadRequired',
	'enable remote',
	'reloadRequired',
	'postEnableTooltip',
	'reloadRequired',
	'postEnableTooltip',
	'reloadRequired',
	'postDisableTooltip',
	'reloadRequired',
	'postEnableTooltip',
	'reloadRequired',
	'postEnableTooltip',
	'installExtensionCompletedAndReloadRequired',
	'current',
	'color theme',
	'select color theme',
	'file icon theme',
	'select file icon theme',
	'product icon theme',
	'select product icon theme',
	'showRecommendedExtension',
	'installRecommendedExtension',
	'ignoreExtensionRecommendation',
	'undo',
	'search recommendations',
	'OpenExtensionsFile.failed',
	'configureWorkspaceRecommendedExtensions',
	'configureWorkspaceFolderRecommendedExtensions',
	'updated',
	'installed',
	'uninstalled',
	'enabled',
	'disabled',
	'malicious tooltip',
	{ key: 'malicious', comment: ['Refers to a malicious extension'] },
	'malicious tooltip',
	'ignored',
	'synced',
	'sync',
	'do not sync',
	'extension enabled on remote',
	'globally enabled',
	'workspace enabled',
	'globally disabled',
	'workspace disabled',
	'disabled because of virtual workspace',
	'Install language pack also in remote server',
	'Install language pack also locally',
	'Install in other server to enable',
	'disabled because of extension kind',
	'disabled locally',
	'disabled remotely',
	'extension disabled because of trust requirement',
	'reinstall',
	'selectExtensionToReinstall',
	'ReinstallAction.successReload',
	'ReinstallAction.success',
	'InstallVSIXAction.reloadNow',
	'install previous version',
	'selectExtension',
	'current',
	'selectVersion',
	'InstallAnotherVersionExtensionAction.successReload',
	'InstallAnotherVersionExtensionAction.success',
	'InstallAnotherVersionExtensionAction.reloadNow',
	'select extensions to install',
	'no local extensions',
	'installing extensions',
	'finished installing',
	'select and install local extensions',
	'install local extensions title',
	'select and install remote extensions',
	'install remote extensions',
	'extensionButtonProminentBackground',
	'extensionButtonProminentForeground',
	'extensionButtonProminentHoverBackground'
]);