/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Extension name",
	"Extension identifier",
	"Preview",
	"Preview",
	"Built-in",
	"Publisher name",
	"Install count",
	"Rating",
	'Repository',
	'License',
	'Version',
	"Details",
	"Extension details, rendered from the extension's 'README.md' file",
	"Feature Contributions",
	"Lists contributions to VS Code by this extension",
	"Changelog",
	"Extension update history, rendered from the extension's 'CHANGELOG.md' file",
	"Dependencies",
	"Lists extensions this extension depends on",
	"Extension Pack",
	"Lists extensions those will be installed together with this extension",
	"You have chosen not to receive recommendations for this extension.",
	"No README available.",
	"Extension Pack ({0})",
	"No README available.",
	"No Changelog available.",
	"No Contributions",
	"No Contributions",
	"No Dependencies",
	"No Extensions",
	"Settings ({0})",
	"Name",
	"Description",
	"Default",
	"Debuggers ({0})",
	"Name",
	"Type",
	"View Containers ({0})",
	"ID",
	"Title",
	"Where",
	"Views ({0})",
	"ID",
	"Name",
	"Where",
	"Localizations ({0})",
	"Language Id",
	"Language Name",
	"Language Name (Localized)",
	"Custom Editors ({0})",
	"View Type",
	"Priority",
	"Filename Pattern",
	"Code Actions ({0})",
	"Title",
	"Kind",
	"Description",
	"Languages",
	"Authentication ({0})",
	"Label",
	"Id",
	"Color Themes ({0})",
	"File Icon Themes ({0})",
	"Product Icon Themes ({0})",
	"Colors ({0})",
	"Id",
	"Description",
	"Dark Default",
	"Light Default",
	"High Contrast Default",
	"JSON Validation ({0})",
	"File Match",
	"Schema",
	"Commands ({0})",
	"Name",
	"Description",
	"Keyboard Shortcuts",
	"Menu Contexts",
	"Languages ({0})",
	"ID",
	"Name",
	"File Extensions",
	"Grammar",
	"Snippets",
	"Activation Events ({0})",
	"Find",
	"Find Next",
	"Find Previous"
]);