/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'Test',
	'Unhide Test',
	'Hide Test',
	'Debug Test',
	'Run Test',
	'Run Selected Tests',
	'Debug Selected Tests',
	'Discovering Tests',
	'Run All Tests',
	'No tests found in this workspace. You may need to install a test provider extension',
	'Debug All Tests',
	'No debuggable tests found in this workspace. You may need to install a test provider extension',
	"Cancel Test Run",
	"View as List",
	"View as Tree",
	"Sort by Name",
	"Sort by Location",
	"Show Output",
	"Collapse All Tests",
	"Refresh Tests",
	"Clear All Results",
	"Go to Test",
	"Turn On Auto Run",
	"Turn Off Auto Run",
	"Run Test at Cursor",
	"Debug Test at Cursor",
	"Run Tests in Current File",
	"Debug Tests in Current File",
	"Rerun Failed Tests",
	"Debug Failed Tests",
	"Rerun Last Run",
	"Debug Last Run",
	"Search for Test Extension"
]);