/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'testing.category',
	'unhideTest',
	'hideTest',
	'debug test',
	'run test',
	'runSelectedTests',
	'debugSelectedTests',
	'discoveringTests',
	'runAllTests',
	'noTestProvider',
	'debugAllTests',
	'noDebugTestProvider',
	'testing.cancelRun',
	'testing.viewAsList',
	'testing.viewAsTree',
	'testing.sortByName',
	'testing.sortByLocation',
	'testing.showMostRecentOutput',
	'testing.collapseAll',
	'testing.refresh',
	'testing.clearResults',
	'testing.editFocusedTest',
	'testing.turnOnAutoRun',
	'testing.turnOffAutoRun',
	'testing.runAtCursor',
	'testing.debugAtCursor',
	'testing.runCurrentFile',
	'testing.debugCurrentFile',
	'testing.reRunFailTests',
	'testing.debugFailTests',
	'testing.reRunLastRun',
	'testing.debugLastRun',
	'testing.searchForTestExtension'
]);