/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'terminalProfile.path',
	'terminalProfile.args',
	'terminalProfile.overrideName',
	'terminalProfile.icon',
	'terminalProfile.env',
	'terminalIntegratedConfigurationTitle',
	'terminal.integrated.sendKeybindingsToShell',
	{
				key: 'terminal.integrated.automationShell.linux',
				comment: ['{0} and {1} are the `shell` and `shellArgs` settings keys']
			},
	{
				key: 'terminal.integrated.automationShell.osx',
				comment: ['{0} and {1} are the `shell` and `shellArgs` settings keys']
			},
	{
				key: 'terminal.integrated.automationShell.windows',
				comment: ['{0} and {1} are the `shell` and `shellArgs` settings keys']
			},
	'terminal.integrated.shellArgs.linux',
	'terminal.integrated.shellArgs.osx',
	'terminal.integrated.shellArgs.windows',
	'terminal.integrated.shellArgs.windows',
	'terminal.integrated.shellArgs.windows.string',
	{
					key: 'terminal.integrated.profiles.windows',
					comment: ['{0}, {1}, and {2} are the `source`, `path` and optional `args` settings keys']
				},
	'terminalProfile.windowsSource',
	'terminalProfile.overrideName',
	'terminalProfile.icon',
	'terminalProfile.env',
	{
					key: 'terminal.integrated.profile.osx',
					comment: ['{0} and {1} are the `path` and optional `args` settings keys']
				},
	{
					key: 'terminal.integrated.profile.linux',
					comment: ['{0} and {1} are the `path` and optional `args` settings keys']
				},
	'terminal.integrated.defaultProfile.linux',
	'terminal.integrated.defaultProfile.osx',
	'terminal.integrated.defaultProfile.windows',
	'terminal.integrated.useWslProfiles',
	'terminal.integrated.tabs.enabled',
	'terminal.integrated.tabs.hideCondition',
	'terminal.integrated.tabs.hideCondition.never',
	'terminal.integrated.tabs.hideCondition.singleTerminal',
	'terminal.integrated.tabs.showActiveTerminal',
	'terminal.integrated.tabs.showActiveTerminal.always',
	'terminal.integrated.tabs.showActiveTerminal.singleTerminal',
	'terminal.integrated.tabs.showActiveTerminal.singleTerminalOrNarrow',
	'terminal.integrated.tabs.showActiveTerminal.never',
	'terminal.integrated.tabs.location.left',
	'terminal.integrated.tabs.location.right',
	'terminal.integrated.tabs.location',
	'terminal.integrated.tabs.focusMode.singleClick',
	'terminal.integrated.tabs.focusMode.doubleClick',
	'terminal.integrated.tabs.focusMode',
	'terminal.integrated.macOptionIsMeta',
	'terminal.integrated.macOptionClickForcesSelection',
	'terminal.integrated.altClickMovesCursor',
	'terminal.integrated.copyOnSelection',
	'terminal.integrated.drawBoldTextInBrightColors',
	'terminal.integrated.fontFamily',
	'terminal.integrated.fontSize',
	'terminal.integrated.letterSpacing',
	'terminal.integrated.lineHeight',
	'terminal.integrated.minimumContrastRatio',
	'terminal.integrated.fastScrollSensitivity',
	'terminal.integrated.mouseWheelScrollSensitivity',
	'terminal.integrated.bellDuration',
	'terminal.integrated.fontWeightError',
	'terminal.integrated.fontWeight',
	'terminal.integrated.fontWeightError',
	'terminal.integrated.fontWeightBold',
	'terminal.integrated.cursorBlinking',
	'terminal.integrated.cursorStyle',
	'terminal.integrated.cursorWidth',
	'terminal.integrated.scrollback',
	'terminal.integrated.detectLocale',
	'terminal.integrated.detectLocale.auto',
	'terminal.integrated.detectLocale.off',
	'terminal.integrated.detectLocale.on',
	'terminal.integrated.gpuAcceleration.auto',
	'terminal.integrated.gpuAcceleration.on',
	'terminal.integrated.gpuAcceleration.off',
	'terminal.integrated.gpuAcceleration',
	'terminal.integrated.rightClickBehavior.default',
	'terminal.integrated.rightClickBehavior.copyPaste',
	'terminal.integrated.rightClickBehavior.paste',
	'terminal.integrated.rightClickBehavior.selectWord',
	'terminal.integrated.rightClickBehavior',
	'terminal.integrated.cwd',
	'terminal.integrated.confirmOnExit',
	'terminal.integrated.enableBell',
	'terminal.integrated.commandsToSkipShell',
	'terminal.integrated.allowChords',
	'terminal.integrated.allowMnemonics',
	'terminal.integrated.inheritEnv',
	'terminal.integrated.env.osx',
	'terminal.integrated.env.linux',
	'terminal.integrated.env.windows',
	'terminal.integrated.environmentChangesIndicator',
	'terminal.integrated.environmentChangesIndicator.off',
	'terminal.integrated.environmentChangesIndicator.on',
	'terminal.integrated.environmentChangesIndicator.warnonly',
	'terminal.integrated.environmentChangesRelaunch',
	'terminal.integrated.showExitAlert',
	'terminal.integrated.splitCwd',
	'terminal.integrated.splitCwd.workspaceRoot',
	'terminal.integrated.splitCwd.initial',
	'terminal.integrated.splitCwd.inherited',
	'terminal.integrated.windowsEnableConpty',
	'terminal.integrated.wordSeparators',
	'terminal.integrated.experimentalUseTitleEvent',
	'terminal.integrated.enableFileLinks',
	'terminal.integrated.unicodeVersion.six',
	'terminal.integrated.unicodeVersion.eleven',
	'terminal.integrated.unicodeVersion',
	'terminal.integrated.experimentalLinkProvider',
	'terminal.integrated.localEchoLatencyThreshold',
	'terminal.integrated.localEchoExcludePrograms',
	'terminal.integrated.localEchoStyle',
	'terminal.integrated.enablePersistentSessions',
	'terminal.integrated.allowWorkspaceConfiguration',
	'terminalIntegratedConfigurationTitle',
	'terminal.integrated.shell.linux.noDefault',
	'terminal.integrated.shell.osx.noDefault',
	'terminal.integrated.shell.windows.noDefault',
	'terminal.integrated.shell.linux',
	'terminal.integrated.shell.osx',
	'terminal.integrated.shell.windows'
]);