/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'A single path to a shell executable or an array of paths that will be used as fallbacks when one fails.',
	'An optional set of arguments to run the shell executable with.',
	'Controls whether or not the profile name overrides the auto detected one.',
	'A codicon ID to associate with this terminal.',
	"An object with environment variables that will be added to the terminal profile process. Set to `null` to delete environment variables from the base environment.",
	"Integrated Terminal",
	"Dispatches most keybindings to the terminal instead of the workbench, overriding `#terminal.integrated.commandsToSkipShell#`, which can be used alternatively for fine tuning.",
	"A path that when set will override {0} and ignore {1} values for automation-related terminal usage like tasks and debug.",
	"A path that when set will override {0} and ignore {1} values for automation-related terminal usage like tasks and debug.",
	"A path that when set will override {0} and ignore {1} values for automation-related terminal usage like tasks and debug.",
	"The command line arguments to use when on the Linux terminal. [Read more about configuring the shell](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration).",
	"The command line arguments to use when on the macOS terminal. [Read more about configuring the shell](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration).",
	"The command line arguments to use when on the Windows terminal. [Read more about configuring the shell](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration).",
	"The command line arguments to use when on the Windows terminal. [Read more about configuring the shell](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration).",
	"The command line arguments in [command-line format](https://msdn.microsoft.com/en-au/08dfcab2-eb6e-49a4-80eb-87d4076c98c6) to use when on the Windows terminal. [Read more about configuring the shell](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration).",
	"The Windows profiles to present when creating a new terminal via the terminal dropdown. Set to null to exclude them, use the {0} property to use the default detected configuration. Or, set the {1} and optional {2}",
	'A profile source that will auto detect the paths to the shell.',
	'Controls whether or not the profile name overrides the auto detected one.',
	'A codicon ID to associate with this terminal.',
	"An object with environment variables that will be added to the terminal profile process. Set to `null` to delete environment variables from the base environment.",
	"The macOS profiles to present when creating a new terminal via the terminal dropdown. When set, these will override the default detected profiles. They are comprised of a {0} and optional {1}",
	"The Linux profiles to present when creating a new terminal via the terminal dropdown. When set, these will override the default detected profiles. They are comprised of a {0} and optional {1}",
	'The default profile used on Linux. When set to a valid profile name, this will override the values of `terminal.integrated.shell.osx` and `terminal.integrated.shellArgs.osx`.',
	'The default profile used on macOS. When set to a valid profile name, this will override the values of `terminal.integrated.shell.osx` and `terminal.integrated.shellArgs.osx`.',
	'The default profile used on Windows. When set to a valid profile name, this will override the values of `terminal.integrated.shell.windows` and `terminal.integrated.shellArgs.windows`.',
	'Controls whether or not WSL distros are shown in the terminal dropdown',
	'Controls whether terminal tabs display as a list to the side of the terminal. When this is disabled a dropdown will display instead.',
	'Controls whether the terminal tabs view will hide under certain conditions.',
	"Never hide the terminal tabs view",
	"Hide the terminal tabs view when there is only a single terminal opened",
	'Shows the active terminal information in the view, this is particularly useful when the title within the tabs aren\'t visible.',
	"Always show the active terminal",
	"Show the active terminal when it is the only terminal opened",
	"Show the active terminal when it is the only terminal opened or when the tabs view is in its narrow textless state",
	"Never show the active terminal",
	"Show the terminal tabs view to the left of the terminal",
	"Show the terminal tabs view to the right of the terminal",
	"Controls the location of the terminal tabs, either to the left or right of the actual terminal(s).",
	"Focus the terminal when clicking a terminal tab",
	"Focus the terminal when double clicking a terminal tab",
	"Controls whether focusing the terminal of a tab happens on double or single click.",
	"Controls whether to treat the option key as the meta key in the terminal on macOS.",
	"Controls whether to force selection when using Option+click on macOS. This will force a regular (line) selection and disallow the use of column selection mode. This enables copying and pasting using the regular terminal selection, for example, when mouse mode is enabled in tmux.",
	"If enabled, alt/option + click will reposition the prompt cursor to underneath the mouse when `#editor.multiCursorModifier#` is set to `'alt'` (the default value). This may not work reliably depending on your shell.",
	"Controls whether text selected in the terminal will be copied to the clipboard.",
	"Controls whether bold text in the terminal will always use the \"bright\" ANSI color variant.",
	"Controls the font family of the terminal, this defaults to `#editor.fontFamily#`'s value.",
	"Controls the font size in pixels of the terminal.",
	"Controls the letter spacing of the terminal, this is an integer value which represents the amount of additional pixels to add between characters.",
	"Controls the line height of the terminal, this number is multiplied by the terminal font size to get the actual line-height in pixels.",
	"When set the foreground color of each cell will change to try meet the contrast ratio specified. Example values:\n\n- 1: The default, do nothing.\n- 4.5: [WCAG AA compliance (minimum)](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html).\n- 7: [WCAG AAA compliance (enhanced)](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast7.html).\n- 21: White on black or black on white.",
	"Scrolling speed multiplier when pressing `Alt`.",
	"A multiplier to be used on the `deltaY` of mouse wheel scroll events.",
	"The number of milliseconds to show the bell within a terminal tab when triggered.",
	"Only \"normal\" and \"bold\" keywords or numbers between 1 and 1000 are allowed.",
	"The font weight to use within the terminal for non-bold text. Accepts \"normal\" and \"bold\" keywords or numbers between 1 and 1000.",
	"Only \"normal\" and \"bold\" keywords or numbers between 1 and 1000 are allowed.",
	"The font weight to use within the terminal for bold text. Accepts \"normal\" and \"bold\" keywords or numbers between 1 and 1000.",
	"Controls whether the terminal cursor blinks.",
	"Controls the style of terminal cursor.",
	"Controls the width of the cursor when `#terminal.integrated.cursorStyle#` is set to `line`.",
	"Controls the maximum amount of lines the terminal keeps in its buffer.",
	"Controls whether to detect and set the `$LANG` environment variable to a UTF-8 compliant option since VS Code's terminal only supports UTF-8 encoded data coming from the shell.",
	"Set the `$LANG` environment variable if the existing variable does not exist or it does not end in `'.UTF-8'`.",
	"Do not set the `$LANG` environment variable.",
	"Always set the `$LANG` environment variable.",
	"Let VS Code detect which renderer will give the best experience.",
	"Enable GPU acceleration within the terminal.",
	"Disable GPU acceleration within the terminal.",
	"Controls whether the terminal will leverage the GPU to do its rendering.",
	"Show the context menu.",
	"Copy when there is a selection, otherwise paste.",
	"Paste on right click.",
	"Select the word under the cursor and show the context menu.",
	"Controls how terminal reacts to right click.",
	"An explicit start path where the terminal will be launched, this is used as the current working directory (cwd) for the shell process. This may be particularly useful in workspace settings if the root directory is not a convenient cwd.",
	"Controls whether to confirm on exit if there are active terminal sessions.",
	"Controls whether the terminal bell is enabled, this shows up as a visual bell next to the terminal's name.",
	"A set of command IDs whose keybindings will not be sent to the shell but instead always be handled by VS Code. This allows keybindings that would normally be consumed by the shell to act instead the same as when the terminal is not focused, for example `Ctrl+P` to launch Quick Open.\n\n&nbsp;\n\nMany commands are skipped by default. To override a default and pass that command's keybinding to the shell instead, add the command prefixed with the `-` character. For example add `-workbench.action.quickOpen` to allow `Ctrl+P` to reach the shell.\n\n&nbsp;\n\nThe following list of default skipped commands is truncated when viewed in Settings Editor. To see the full list, [open the default settings JSON](command:workbench.action.openRawDefaultSettings 'Open Default Settings (JSON)') and search for the first command from the list below.\n\n&nbsp;\n\nDefault Skipped Commands:\n\n{0}",
	"Whether or not to allow chord keybindings in the terminal. Note that when this is true and the keystroke results in a chord it will bypass `#terminal.integrated.commandsToSkipShell#`, setting this to false is particularly useful when you want ctrl+k to go to your shell (not VS Code).",
	"Whether to allow menubar mnemonics (eg. alt+f) to trigger the open the menubar. Note that this will cause all alt keystrokes to skip the shell when true. This does nothing on macOS.",
	"Whether new shells should inherit their environment from VS Code. This is not supported on Windows.",
	"Object with environment variables that will be added to the VS Code process to be used by the terminal on macOS. Set to `null` to delete the environment variable.",
	"Object with environment variables that will be added to the VS Code process to be used by the terminal on Linux. Set to `null` to delete the environment variable.",
	"Object with environment variables that will be added to the VS Code process to be used by the terminal on Windows. Set to `null` to delete the environment variable.",
	"Whether to display the environment changes indicator on each terminal which explains whether extensions have made, or want to make changes to the terminal's environment.",
	"Disable the indicator.",
	"Enable the indicator.",
	"Only show the warning indicator when a terminal's environment is 'stale', not the information indicator that shows a terminal has had its environment modified by an extension.",
	"Whether to relaunch terminals automatically if extension want to contribute to their environment and have not been interacted with yet.",
	"Controls whether to show the alert \"The terminal process terminated with exit code\" when exit code is non-zero.",
	"Controls the working directory a split terminal starts with.",
	"A new split terminal will use the workspace root as the working directory. In a multi-root workspace a choice for which root folder to use is offered.",
	"A new split terminal will use the working directory that the parent terminal started with.",
	"On macOS and Linux, a new split terminal will use the working directory of the parent terminal. On Windows, this behaves the same as initial.",
	"Whether to use ConPTY for Windows terminal process communication (requires Windows 10 build number 18309+). Winpty will be used if this is false.",
	"A string containing all characters to be considered word separators by the double click to select word feature.",
	"An experimental setting that will use the terminal title event for the dropdown title. This setting will only apply to new terminals.",
	"Whether to enable file links in the terminal. Links can be slow when working on a network drive in particular because each file link is verified against the file system. Changing this will take effect only in new terminals.",
	"Version 6 of unicode, this is an older version which should work better on older systems.",
	"Version 11 of unicode, this version provides better support on modern systems that use modern versions of unicode.",
	"Controls what version of unicode to use when evaluating the width of characters in the terminal. If you experience emoji or other wide characters not taking up the right amount of space or backspace either deleting too much or too little then you may want to try tweaking this setting.",
	"An experimental setting that aims to improve link detection in the terminal by improving when links are detected and by enabling shared link detection with the editor. Currently this only supports web links.",
	"Experimental: length of network delay, in milliseconds, where local edits will be echoed on the terminal without waiting for server acknowledgement. If '0', local echo will always be on, and if '-1' it will be disabled.",
	"Experimental: local echo will be disabled when any of these program names are found in the terminal title.",
	"Experimental: terminal style of locally echoed text; either a font style or an RGB color.",
	"Persist terminal sessions for the workspace across window reloads.",
	"Allows shell and profile settings to be pick up from a workspace.",
	"Integrated Terminal",
	"The path of the shell that the terminal uses on Linux. [Read more about configuring the shell](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration).",
	"The path of the shell that the terminal uses on macOS. [Read more about configuring the shell](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration).",
	"The path of the shell that the terminal uses on Windows. [Read more about configuring the shell](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration).",
	"The path of the shell that the terminal uses on Linux (default: {0}). [Read more about configuring the shell](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration).",
	"The path of the shell that the terminal uses on macOS (default: {0}). [Read more about configuring the shell](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration).",
	"The path of the shell that the terminal uses on Windows (default: {0}). [Read more about configuring the shell](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration)."
]);