/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'trustedHeaderWorkspace',
	'trustedHeaderFolder',
	'untrustedHeaderWorkspace',
	'untrustedHeaderFolder',
	'trustedDescription',
	'untrustedDescription',
	'trustedWorkspace',
	'trustedFolder',
	'trustedWorkspaceSubtitle',
	'trustedFolderSubtitle',
	'trustedTasks',
	'trustedDebugging',
	'trustedSettings',
	'trustedExtensions',
	'untrustedWorkspace',
	'untrustedWorkspaceSubtitle',
	'untrustedFolderSubtitle',
	'untrustedTasks',
	'untrustedDebugging',
	'untrustedSettings',
	'no untrustedSettings',
	'untrustedExtensions',
	'trustButton',
	'trustParentButton',
	'dontTrustButton',
	'untrustedWorkspaceReason',
	'untrustedFolderReason',
	'workspaceTrustSettingModificationMessage',
	'workspaceTrustTransitionDetail',
	'workspaceTrustTransitionPrimaryButton',
	'workspaceTrustTransitionSecondaryButton'
]);