/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Do you trust the authors of the files in this workspace?",
	"Do you trust the authors of the files in this folder?",
	"I trust the authors of all files in the parent folder",
	"Yes, I trust the authors",
	"Trust folder and enable all features",
	"Trust workspace and enable all features",
	"No, I don't trust the authors",
	"Browse folder in restricted mode",
	"Browse workspace in restricted mode",
	"{0} provides advanced editing features that may automatically execute files in this workspace.",
	"{0} provides advanced editing features that may automatically execute files in this folder.",
	"If you don't trust the authors of these files, we recommend to continue in restricted mode as the files may be malicious. See [our docs](https://aka.ms/vscode-workspace-trust) to learn more.",
	"A feature you are trying to use may be a security risk if you do not trust the source of the files or folders you currently have open.",
	"Trust Workspace & Continue",
	"Trust Folder & Continue",
	"Manage",
	"Cancel",
	"If you don't trust the authors of these files, we do not recommend continuing as the files may be malicious. See [our docs](https://aka.ms/vscode-workspace-trust) to learn more.",
	"Do you trust the authors of the files in this folder?",
	'Yes',
	'No',
	"You are adding files to a trusted workspace that are not currently trusted. Do you trust the authors of these new files?",
	"Workspace Trust",
	"This workspace is trusted.",
	"Restricted Mode: Some features are disabled because this workspace is not trusted.",
	"This workspace is trusted.",
	"Some features are disabled because this workspace is not trusted.",
	"Workspace Trust Editor",
	"Manage Workspace Trust",
	"Workspaces",
	"Manage Workspace Trust (1)",
	"Security",
	"Controls whether or not workspace trust is enabled within VS Code.",
	"Controls when the startup prompt to trust a workspace is shown.",
	"Ask for trust every time an untrusted workspace is opened.",
	"Ask for trust the first time an untrusted workspace is opened.",
	"Do not ask for trust when an untrusted workspace is opened."
]);