/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"You trust this workspace",
	"You trust this folder",
	"You are in restricted mode",
	"You are in Restricted Mode",
	"All features are enabled because trust has been granted to the workspace. [Learn more](https://aka.ms/vscode-workspace-trust).",
	"{0} is in a restricted mode intended for safe code browsing. [Learn more](https://aka.ms/vscode-workspace-trust).",
	"In a trusted workspace",
	"In a Trusted Folder",
	"You trust the authors of the files in the current workspace. All features are enabled:",
	"You trust the authors of the files in the current folder. All features are enabled:",
	"Tasks will be allowed to run",
	"Debugging will be enabled",
	"All workspace settings will be applied",
	"All extensions will be enabled",
	"In Restricted Mode",
	"You do not trust the authors of the files in the current workspace. The following features are disabled:",
	"You do not trust the authors of the files in the current folder. The following features are disabled:",
	"Tasks will be disabled",
	"Debugging will be disabled",
	"[{0} workspace settings](command:{1}) will not be applied",
	"Workspace settings requiring trust will not be applied",
	"[{0} extensions](command:{1}) will be disabled or have limited functionality",
	"Trust",
	"Trust All in Parent Folder",
	"Don't Trust",
	"This workspace is trusted via one or more of the trusted folders below.",
	"This folder is trusted via one or more of the trusted folders below.",
	"Update Workspace Trust Settings",
	"In order to safely complete this action, all affected windows will have to be reloaded. Are you sure you want to proceed with this action?",
	"Yes",
	"No"
]);