/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'editorConfigurationTitle',
	'tabSize',
	'insertSpaces',
	'detectIndentation',
	'trimAutoWhitespace',
	'largeFileOptimizations',
	'wordBasedSuggestions',
	'wordBasedSuggestionsMode.currentDocument',
	'wordBasedSuggestionsMode.matchingDocuments',
	'wordBasedSuggestionsMode.allDocuments',
	'wordBasedSuggestionsMode',
	'semanticHighlighting.true',
	'semanticHighlighting.false',
	'semanticHighlighting.configuredByTheme',
	'semanticHighlighting.enabled',
	'stablePeek',
	'maxTokenizationLineLength',
	'maxComputationTime',
	'sideBySide',
	'ignoreTrimWhitespace',
	'renderIndicators',
	'codeLens',
	'wordWrap.off',
	'wordWrap.on',
	'wordWrap.inherit'
]);