/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'turn on sync with category',
	'stop sync',
	'configure sync',
	'showConflicts',
	'showKeybindingsConflicts',
	'showSnippetsConflicts',
	'sync now',
	'syncing',
	'synced with time',
	'sync settings',
	'show synced data',
	'conflicts detected',
	'replace remote',
	'replace local',
	'show conflicts',
	'accept failed',
	'accept failed',
	'session expired',
	'turn on sync',
	'turned off',
	'turn on sync',
	'too large',
	'error upgrade required',
	'operationId',
	'error reset required',
	'reset',
	'show synced data action',
	'service switched to insiders',
	'service switched to stable',
	'using separate service',
	'service changed and turned off',
	'turn on sync',
	'operationId',
	'open file',
	'errorInvalidConfiguration',
	'open file',
	'has conflicts',
	'turning on syncing',
	'sign in to sync',
	'no authentication providers',
	'too large while starting sync',
	'error upgrade required while starting sync',
	'operationId',
	'error reset required while starting sync',
	'reset',
	'show synced data action',
	'auth failed',
	'turn on failed with user data sync error',
	{ key: 'turn on failed', comment: ['Substitution is for error reason'] },
	'sync preview message',
	'turn on',
	'open doc',
	'cancel',
	'sign in and turn on',
	'configure and turn on sync detail',
	'per platform',
	'configure sync',
	'configure sync placeholder',
	'turn off sync confirmation',
	'turn off sync detail',
	{ key: 'turn off', comment: ['&& denotes a mnemonic'] },
	'turn off sync everywhere',
	{ key: 'leftResourceName', comment: ['remote as in file in cloud'] },
	'merges',
	'sideBySideLabels',
	'sideBySideDescription',
	'switchSyncService.title',
	'switchSyncService.description',
	'default',
	'insiders',
	'stable',
	'global activity turn on sync',
	'global activity turn on sync',
	'global activity turn on sync',
	'turnin on sync',
	'sign in global',
	'sign in accounts',
	'resolveConflicts_global',
	'resolveConflicts_global',
	'resolveKeybindingsConflicts_global',
	'resolveKeybindingsConflicts_global',
	'resolveSnippetsConflicts_global',
	'resolveSnippetsConflicts_global',
	'sync is on',
	'workbench.action.showSyncRemoteBackup',
	'turn off failed',
	'configure',
	'show sync log title',
	'show sync log toolrip',
	'workbench.actions.syncData.reset',
	'accept remote',
	'accept merges',
	'accept remote button',
	'accept merges button',
	'Sync accept remote',
	'Sync accept merges',
	'confirm replace and overwrite local',
	'confirm replace and overwrite remote',
	'update conflicts',
	'accept failed'
]);