/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Remote Server",
	"UI extension kind. In a remote window, such extensions are enabled only when available on the local machine.",
	"Workspace extension kind. In a remote window, such extensions are enabled only when available on the remote.",
	"Web worker extension kind. Such an extension can execute in a web worker extension host.",
	"Remote",
	"Override the kind of an extension. `ui` extensions are installed and run on the local machine while `workspace` extensions are run on the remote. By overriding an extension's default kind using this setting, you specify if that extension should be installed and enabled locally or remotely.",
	"Restores the ports you forwarded in a workspace.",
	"When enabled, new running processes are detected and ports that they listen on are automatically forwarded.",
	"Sets the source from which ports are automatically forwarded when `remote.autoForwardPorts` is true. On Windows and Mac remotes, the `process` option has no effect and `output` will be used. Requires a reload to take effect.",
	"Ports will be automatically forwarded when discovered by watching for processes that are started and include a port.",
	"Ports will be automatically forwarded when discovered by reading terminal and debug output. Not all processes that use ports will print to the integrated terminal or debug console, so some ports will be missed. Ports forwarded based on output will not be \"un-forwarded\" until reload or until the port is closed by the user in the Ports view.",
	"A port, range of ports (ex. \"40000-55000\"), or regular expression (ex. \".+\\\\/server.js\").  For a port number or range, the attributes will apply to that port number or range of port numbers. Attributes which use a regular expression will apply to ports whose associated process command line matches the expression.",
	"Shows a notification when a port is automatically forwarded.",
	"Opens the browser when the port is automatically forwarded. Depending on your settings, this could open an embedded browser.",
	"Opens a preview in the same window when the port is automatically forwarded.",
	"Shows no notification and takes no action when this port is automatically forwarded.",
	"This port will not be automatically forwarded.",
	"Defines the action that occurs when the port is discovered for automatic forwarding",
	"Automatically prompt for elevation (if needed) when this port is forwarded. Elevate is required if the local port is a privileged port.",
	"Label that will be shown in the UI for this port.",
	"Application",
	"Application",
	"Set properties that are applied when a specific port number is forwarded. For example:\n\n```\n\"3000\": {\n  \"label\": \"Application\"\n},\n\"40000-55000\": {\n  \"onAutoForward\": \"ignore\"\n},\n\".+\\\\/server.js\": {\n \"onAutoForward\": \"openPreview\"\n}\n```",
	"Must be a port number, range of port numbers, or regular expression.",
	"Shows a notification when a port is automatically forwarded.",
	"Opens the browser when the port is automatically forwarded. Depending on your settings, this could open an embedded browser.",
	"Opens a preview in the same window when the port is automatically forwarded.",
	"Shows no notification and takes no action when this port is automatically forwarded.",
	"This port will not be automatically forwarded.",
	"Defines the action that occurs when the port is discovered for automatic forwarding",
	"Automatically prompt for elevation (if needed) when this port is forwarded. Elevate is required if the local port is a privileged port.",
	"Label that will be shown in the UI for this port.",
	"Application",
	"Set default properties that are applied to all ports that don't get properties from the setting `remote.portsAttributes`. For example:\n\n```\n{\n  \"onAutoForward\": \"ignore\"\n}\n```"
]);