/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'RemoteHelpInformationExtPoint',
	'RemoteHelpInformationExtPoint.getStarted',
	'RemoteHelpInformationExtPoint.documentation',
	'RemoteHelpInformationExtPoint.feedback',
	'RemoteHelpInformationExtPoint.issues',
	'remote.help.getStarted',
	'remote.help.documentation',
	'remote.help.feedback',
	'remote.help.issues',
	'remote.help.report',
	'pickRemoteExtension',
	'remote.help',
	'remotehelp',
	'remote.explorer',
	'remote.explorer',
	'reconnectionWaitOne',
	'reconnectionWaitMany',
	'reconnectNow',
	'reloadWindow',
	'connectionLost',
	'reconnectionRunning',
	'reconnectionPermanentFailure',
	'reloadWindow',
	'cancel'
]);