/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'textEditor',
	'textDiffEditor',
	'binaryDiffEditor',
	'sideBySideEditor',
	'editorQuickAccessPlaceholder',
	'activeGroupEditorsByMostRecentlyUsedQuickAccess',
	'editorQuickAccessPlaceholder',
	'allEditorsByAppearanceQuickAccess',
	'editorQuickAccessPlaceholder',
	'allEditorsByMostRecentlyUsedQuickAccess',
	'file',
	'splitUp',
	'splitDown',
	'splitLeft',
	'splitRight',
	'close',
	'close',
	'closeOthers',
	'closeRight',
	'closeAllSaved',
	'closeAll',
	'keepOpen',
	'pin',
	'unpin',
	'splitUp',
	'splitDown',
	'splitLeft',
	'splitRight',
	'inlineView',
	'showOpenedEditors',
	'closeAll',
	'closeAllSaved',
	'toggleKeepEditors',
	'run',
	'splitEditorRight',
	'splitEditorDown',
	'splitEditorDown',
	'splitEditorRight',
	'close',
	'closeAll',
	'close',
	'closeAll',
	'unpin',
	'close',
	'unpin',
	'close',
	'previousChangeIcon',
	'nextChangeIcon',
	'toggleWhitespace',
	'navigate.prev.label',
	'navigate.next.label',
	'ignoreTrimWhitespace.label',
	'showTrimWhitespace.label',
	'keepEditor',
	'pinEditor',
	'unpinEditor',
	'closeEditor',
	'closePinnedEditor',
	'closeEditorsInGroup',
	'closeSavedEditors',
	'closeOtherEditors',
	'closeRightEditors',
	'closeEditorGroup',
	{ key: 'miReopenClosedEditor', comment: ['&& denotes a mnemonic'] },
	{ key: 'miClearRecentOpen', comment: ['&& denotes a mnemonic'] },
	{ key: 'miEditorLayout', comment: ['&& denotes a mnemonic'] },
	{ key: 'miSplitEditorUp', comment: ['&& denotes a mnemonic'] },
	{ key: 'miSplitEditorDown', comment: ['&& denotes a mnemonic'] },
	{ key: 'miSplitEditorLeft', comment: ['&& denotes a mnemonic'] },
	{ key: 'miSplitEditorRight', comment: ['&& denotes a mnemonic'] },
	{ key: 'miSingleColumnEditorLayout', comment: ['&& denotes a mnemonic'] },
	{ key: 'miTwoColumnsEditorLayout', comment: ['&& denotes a mnemonic'] },
	{ key: 'miThreeColumnsEditorLayout', comment: ['&& denotes a mnemonic'] },
	{ key: 'miTwoRowsEditorLayout', comment: ['&& denotes a mnemonic'] },
	{ key: 'miThreeRowsEditorLayout', comment: ['&& denotes a mnemonic'] },
	{ key: 'miTwoByTwoGridEditorLayout', comment: ['&& denotes a mnemonic'] },
	{ key: 'miTwoRowsRightEditorLayout', comment: ['&& denotes a mnemonic'] },
	{ key: 'miTwoColumnsBottomEditorLayout', comment: ['&& denotes a mnemonic'] },
	{ key: 'miBack', comment: ['&& denotes a mnemonic'] },
	{ key: 'miForward', comment: ['&& denotes a mnemonic'] },
	{ key: 'miLastEditLocation', comment: ['&& denotes a mnemonic'] },
	{ key: 'miNextEditor', comment: ['&& denotes a mnemonic'] },
	{ key: 'miPreviousEditor', comment: ['&& denotes a mnemonic'] },
	{ key: 'miNextRecentlyUsedEditor', comment: ['&& denotes a mnemonic'] },
	{ key: 'miPreviousRecentlyUsedEditor', comment: ['&& denotes a mnemonic'] },
	{ key: 'miNextEditorInGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miPreviousEditorInGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miNextUsedEditorInGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miPreviousUsedEditorInGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miSwitchEditor', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusFirstGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusSecondGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusThirdGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusFourthGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusFifthGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miNextGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miPreviousGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusLeftGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusRightGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusAboveGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miFocusBelowGroup', comment: ['&& denotes a mnemonic'] },
	{ key: 'miSwitchGroup', comment: ['&& denotes a mnemonic'] }
]);