/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Text Editor",
	"Text Diff Editor",
	"Binary Diff Editor",
	"Side by Side Editor",
	"Type the name of an editor to open it.",
	"Show Editors in Active Group by Most Recently Used",
	"Type the name of an editor to open it.",
	"Show All Opened Editors By Appearance",
	"Type the name of an editor to open it.",
	"Show All Opened Editors By Most Recently Used",
	"File",
	"Split Up",
	"Split Down",
	"Split Left",
	"Split Right",
	"Close",
	"Close",
	"Close Others",
	"Close to the Right",
	"Close Saved",
	"Close All",
	"Keep Open",
	"Pin",
	"Unpin",
	"Split Up",
	"Split Down",
	"Split Left",
	"Split Right",
	"Inline View",
	"Show Opened Editors",
	"Close All",
	"Close Saved",
	"Keep Editors Open",
	"Run",
	"Split Editor Right",
	"Split Editor Down",
	"Split Editor Down",
	"Split Editor Right",
	"Close",
	"Close All",
	"Close",
	"Close All",
	"Unpin",
	"Close",
	"Unpin",
	"Close",
	'Icon for the previous change action in the diff editor.',
	'Icon for the next change action in the diff editor.',
	'Icon for the toggle whitespace action in the diff editor.',
	"Previous Change",
	"Next Change",
	"Ignore Leading/Trailing Whitespace Differences",
	"Show Leading/Trailing Whitespace Differences",
	"Keep Editor",
	"Pin Editor",
	"Unpin Editor",
	"Close Editor",
	"Close Pinned Editor",
	"Close All Editors in Group",
	"Close Saved Editors in Group",
	"Close Other Editors in Group",
	"Close Editors to the Right in Group",
	"Close Editor Group",
	"&&Reopen Closed Editor",
	"&&Clear Recently Opened",
	"Editor &&Layout",
	"Split &&Up",
	"Split &&Down",
	"Split &&Left",
	"Split &&Right",
	"&&Single",
	"&&Two Columns",
	"T&&hree Columns",
	"T&&wo Rows",
	"Three &&Rows",
	"&&Grid (2x2)",
	"Two R&&ows Right",
	"Two &&Columns Bottom",
	"&&Back",
	"&&Forward",
	"&&Last Edit Location",
	"&&Next Editor",
	"&&Previous Editor",
	"&&Next Used Editor",
	"&&Previous Used Editor",
	"&&Next Editor in Group",
	"&&Previous Editor in Group",
	"&&Next Used Editor in Group",
	"&&Previous Used Editor in Group",
	"Switch &&Editor",
	"Group &&1",
	"Group &&2",
	"Group &&3",
	"Group &&4",
	"Group &&5",
	"&&Next Group",
	"&&Previous Group",
	"Group &&Left",
	"Group &&Right",
	"Group &&Above",
	"Group &&Below",
	"Switch &&Group"
]);