/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'releaseNotes',
	'update.noReleaseNotesOnline',
	'releaseNotes',
	'showReleaseNotes',
	'read the release notes',
	'releaseNotes',
	'licenseChanged',
	'updateIsReady',
	'checkingForUpdates',
	'update service',
	'noUpdatesAvailable',
	'ok',
	'thereIsUpdateAvailable',
	'download update',
	'later',
	'releaseNotes',
	'updateAvailable',
	'installUpdate',
	'later',
	'releaseNotes',
	'updateInstalling',
	'updateNow',
	'later',
	'releaseNotes',
	'updateAvailableAfterRestart',
	'checkForUpdates',
	'checkingForUpdates',
	'download update_1',
	'DownloadingUpdate',
	'installUpdate...',
	'installingUpdate',
	'restartToUpdate',
	'switchToInsiders',
	'switchToStable',
	'relaunchMessage',
	'relaunchDetailInsiders',
	'relaunchDetailStable',
	'reload',
	'selectSyncService.message',
	'use insiders',
	'use stable',
	'cancel',
	'selectSyncService.detail',
	'checkForUpdates'
]);