/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Release Notes",
	"This version of {0} does not have release notes online",
	"Release Notes",
	"Show Release Notes",
	"Welcome to {0} v{1}! Would you like to read the Release Notes?",
	"Release Notes",
	"Our license terms have changed, please click [here]({0}) to go through them.",
	"New {0} update available.",
	"Checking for Updates...",
	"Update Service",
	"There are currently no updates available.",
	"OK",
	"There is an available update.",
	"Download Update",
	"Later",
	"Release Notes",
	"There's an update available: {0} {1}",
	"Install Update",
	"Later",
	"Release Notes",
	"{0} {1} is being installed in the background; we'll let you know when it's done.",
	"Update Now",
	"Later",
	"Release Notes",
	"Restart {0} to apply the latest update.",
	"Check for Updates...",
	"Checking for Updates...",
	"Download Update (1)",
	"Downloading Update...",
	"Install Update... (1)",
	"Installing Update...",
	"Restart to Update (1)",
	"Switch to Insiders Version...",
	"Switch to Stable Version...",
	"Changing the version requires a reload to take effect",
	"Press the reload button to switch to the nightly pre-production version of VSCode.",
	"Press the reload button to switch to the monthly released stable version of VSCode.",
	"&&Reload",
	"Choose the settings sync service to use after changing the version",
	"Insiders",
	"Stable (current)",
	"Cancel",
	"The Insiders version of VS Code will synchronize your settings, keybindings, extensions, snippets and UI State using separate insiders settings sync service by default.",
	"Check for Updates..."
]);