/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'treeAriaLabel',
	'fileInputAriaLabel',
	'confirmOverwrite',
	'irreversible',
	{ key: 'replaceButtonLabel', comment: ['&& denotes a mnemonic'] },
	'confirmManyOverwrites',
	'irreversible',
	{ key: 'replaceButtonLabel', comment: ['&& denotes a mnemonic'] },
	'uploadingFiles',
	'overwrite',
	'overwriting',
	'uploadProgressSmallMany',
	'uploadProgressLarge',
	'copyFolders',
	'copyFolder',
	'cancel',
	'copyfolders',
	'copyfolder',
	'addFolders',
	'addFolder',
	'dropFolders',
	'dropFolder',
	'copyFile',
	'copynFile',
	'copyingFile',
	'copyingnFile',
	'confirmRootsMove',
	'confirmMultiMove',
	'confirmRootMove',
	'confirmMove',
	'doNotAskAgain',
	{ key: 'moveButtonLabel', comment: ['&& denotes a mnemonic'] },
	'copy',
	'copying',
	'move',
	'moving'
]);