/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Files Explorer",
	"Type file name. Press Enter to confirm or Escape to cancel.",
	"A file or folder with the name '{0}' already exists in the destination folder. Do you want to replace it?",
	"This action is irreversible!",
	"&&Replace",
	"The following {0} files and/or folders already exist in the destination folder. Do you want to replace them?",
	"This action is irreversible!",
	"&&Replace",
	"Uploading",
	"Overwrite {0}",
	"Overwriting {0}",
	"{0} of {1} files ({2}/s)",
	"{0} ({1} of {2}, {3}/s)",
	"&&Copy Folders",
	"&&Copy Folder",
	"Cancel",
	"Are you sure to want to copy folders?",
	"Are you sure to want to copy '{0}'?",
	"&&Add Folders to Workspace",
	"&&Add Folder to Workspace",
	"Do you want to copy the folders or add the folders to the workspace?",
	"Do you want to copy '{0}' or add '{0}' as a folder to the workspace?",
	"Copy {0}",
	"Copy {0} resources",
	"Copying {0}",
	"Copying {0} resources",
	"Are you sure you want to change the order of multiple root folders in your workspace?",
	"Are you sure you want to move the following {0} files into '{1}'?",
	"Are you sure you want to change the order of root folder '{0}' in your workspace?",
	"Are you sure you want to move '{0}' into '{1}'?",
	"Do not ask me again",
	"&&Move",
	"Copy {0}",
	"Copying {0}",
	"Move {0}",
	"Moving {0}"
]);