/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'walkthroughs',
	'walkthroughs.id',
	'walkthroughs.title',
	'walkthroughs.description',
	'walkthroughs.primary',
	'walkthroughs.when',
	'usesteps',
	'walkthroughs.steps',
	'walkthroughs.steps.id',
	'walkthroughs.steps.title',
	'walkthroughs.steps.description',
	'walkthroughs.steps.button.deprecated',
	'walkthroughs.steps.media',
	'walkthroughs.steps.media.image.path.string',
	'walkthroughs.steps.media.image.path.dark.string',
	'walkthroughs.steps.media.image.path.light.string',
	'walkthroughs.steps.media.image.path.hc.string',
	'walkthroughs.steps.media.altText',
	'walkthroughs.steps.media.markdown.path',
	'walkthroughs.steps.doneOn',
	'walkthroughs.steps.oneOn.command',
	'walkthroughs.steps.when',
	'startEntries',
	'startEntries.title',
	'startEntries.command',
	'startEntries.description',
	'startEntries.when',
	'startEntries.type'
]);