/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'newTab',
	'showPreviousTab',
	'showNextWindowTab',
	'moveWindowTabToNewWindow',
	'mergeAllWindowTabs',
	'toggleWindowTabsBar',
	{ key: 'miCloseWindow', comment: ['&& denotes a mnemonic'] },
	{ key: 'miExit', comment: ['&& denotes a mnemonic'] },
	{ key: 'miZoomIn', comment: ['&& denotes a mnemonic'] },
	{ key: 'miZoomOut', comment: ['&& denotes a mnemonic'] },
	{ key: 'miZoomReset', comment: ['&& denotes a mnemonic'] },
	{ key: 'miReportIssue', comment: ['&& denotes a mnemonic', 'Translate this to "Report Issue in English" in all languages please!'] },
	{ key: 'miOpenProcessExplorerer', comment: ['&& denotes a mnemonic'] },
	'windowConfigurationTitle',
	'window.openWithoutArgumentsInNewWindow.on',
	'window.openWithoutArgumentsInNewWindow.off',
	'openWithoutArgumentsInNewWindow',
	'window.reopenFolders.preserve',
	'window.reopenFolders.all',
	'window.reopenFolders.folders',
	'window.reopenFolders.one',
	'window.reopenFolders.none',
	'restoreWindows',
	'restoreFullscreen',
	'zoomLevel',
	'window.newWindowDimensions.default',
	'window.newWindowDimensions.inherit',
	'window.newWindowDimensions.offset',
	'window.newWindowDimensions.maximized',
	'window.newWindowDimensions.fullscreen',
	'newWindowDimensions',
	'closeWhenEmpty',
	'window.doubleClickIconToClose',
	'titleBarStyle',
	'dialogStyle',
	'window.nativeTabs',
	'window.nativeFullScreen',
	'window.clickThroughInactive',
	'telemetryConfigurationTitle',
	'telemetry.enableCrashReporting',
	'keyboardConfigurationTitle',
	'touchbar.enabled',
	'touchbar.ignored',
	'argv.locale',
	'argv.disableHardwareAcceleration',
	'argv.disableColorCorrectRendering',
	'argv.forceColorProfile',
	'argv.enableCrashReporter',
	'argv.crashReporterId',
	'argv.enebleProposedApi',
	'argv.logLevel',
	'argv.force-renderer-accessibility'
]);