/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'View icon of the Source Control view.',
	"Source Control",
	"No source control providers registered.",
	"Source Control",
	"S&&CM",
	"Source Control Repositories",
	"SCM",
	"Show the diff decorations in all available locations.",
	"Show the diff decorations only in the editor gutter.",
	"Show the diff decorations only in the overview ruler.",
	"Show the diff decorations only in the minimap.",
	"Do not show the diff decorations.",
	"Controls diff decorations in the editor.",
	"Controls the width(px) of diff decorations in gutter (added & modified).",
	"Show the diff decorator in the gutter at all times.",
	"Show the diff decorator in the gutter only on hover.",
	"Controls the visibility of the Source Control diff decorator in the gutter.",
	"Show the inline diff peek view on click.",
	"Do nothing.",
	"Controls the behavior of Source Control diff gutter decorations.",
	"Controls whether inline actions are always visible in the Source Control view.",
	"Show the sum of all Source Control Provider count badges.",
	"Show the count badge of the focused Source Control Provider.",
	"Disable the Source Control count badge.",
	"Controls the count badge on the Source Control icon on the Activity Bar.",
	"Hide Source Control Provider count badges.",
	"Only show count badge for Source Control Provider when non-zero.",
	"Show Source Control Provider count badges.",
	"Controls the count badges on Source Control Provider headers. These headers only appear when there is more than one provider.",
	"Show the repository changes as a tree.",
	"Show the repository changes as a list.",
	"Controls the default Source Control repository view mode.",
	"Controls whether the SCM view should automatically reveal and select files when opening them.",
	"Controls the font for the input message. Use `default` for the workbench user interface font family, `editor` for the `#editor.fontFamily#`'s value, or a custom font family.",
	"Controls the font size for the input message in pixels.",
	"Controls whether repositories should always be visible in the SCM view.",
	"Controls how many repositories are visible in the Source Control Repositories section. Set to `0` to be able to manually resize the view.",
	"SCM: Accept Input",
	"SCM: View Next Commit",
	"SCM: View Previous Commit",
	"Open In Terminal"
]);