/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'sourceControlViewIcon',
	'source control',
	'no open repo',
	'source control',
	{ key: 'miViewSCM', comment: ['&& denotes a mnemonic'] },
	'source control repositories',
	'scmConfigurationTitle',
	'scm.diffDecorations.all',
	'scm.diffDecorations.gutter',
	'scm.diffDecorations.overviewRuler',
	'scm.diffDecorations.minimap',
	'scm.diffDecorations.none',
	'diffDecorations',
	'diffGutterWidth',
	'scm.diffDecorationsGutterVisibility.always',
	'scm.diffDecorationsGutterVisibility.hover',
	'scm.diffDecorationsGutterVisibility',
	'scm.diffDecorationsGutterAction.diff',
	'scm.diffDecorationsGutterAction.none',
	'scm.diffDecorationsGutterAction',
	'alwaysShowActions',
	'scm.countBadge.all',
	'scm.countBadge.focused',
	'scm.countBadge.off',
	'scm.countBadge',
	'scm.providerCountBadge.hidden',
	'scm.providerCountBadge.auto',
	'scm.providerCountBadge.visible',
	'scm.providerCountBadge',
	'scm.defaultViewMode.tree',
	'scm.defaultViewMode.list',
	'scm.defaultViewMode',
	'autoReveal',
	'inputFontFamily',
	'inputFontSize',
	'alwaysShowRepository',
	'providersVisible',
	'scm accept',
	'scm view next commit',
	'scm view previous commit',
	'open in terminal'
]);