/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'hide',
	'show',
	'createOnGitHub',
	'previewOnGitHub',
	'loadingData',
	'rateLimited',
	'similarIssues',
	'open',
	'closed',
	'open',
	'closed',
	'noSimilarIssues',
	'bugReporter',
	'featureRequest',
	'performanceIssue',
	'selectSource',
	'vscode',
	'extension',
	'marketplace',
	'unknown',
	'stepsToReproduce',
	'bugDescription',
	'stepsToReproduce',
	'performanceIssueDesciption',
	'description',
	'featureRequestDescription',
	'pasteData',
	'disabledExtensions',
	'noCurrentExperiments'
]);