/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Show Tabs",
	"Select current working directory for new terminal",
	"Open Help",
	"Create New Integrated Terminal (In Active Workspace)",
	"Create New Integrated Terminal (With Profile)",
	"Select current working directory for new terminal",
	"New Terminal With Profile",
	"Show Tabs",
	"Show Tabs",
	"Focus Previous Pane",
	"Focus Next Pane",
	"Resize Pane Left",
	"Resize Pane Right",
	"Resize Pane Up",
	"Resize Pane Down",
	"Focus Terminal",
	"Focus Terminal Tabs View",
	"Focus Next Terminal",
	"Focus Previous Terminal",
	"Run Selected Text In Active Terminal",
	"Run Active File In Active Terminal",
	'Only files on disk can be run in the terminal',
	"Scroll Down (Line)",
	"Scroll Down (Page)",
	"Scroll to Bottom",
	"Scroll Up (Line)",
	"Scroll Up (Page)",
	"Scroll to Top",
	"Exit Navigation Mode",
	"Focus Previous Line (Navigation Mode)",
	"Focus Next Line (Navigation Mode)",
	"Clear Selection",
	"Change Icon...",
	"Change Icon...",
	"Rename...",
	"Rename...",
	"Focus Find",
	"Hide Find",
	"Attach to Session",
	'There are no unattached terminals to attach to',
	"Switch Active Terminal",
	"Scroll To Previous Command",
	"Scroll To Next Command",
	"Select To Previous Command",
	"Select To Next Command",
	"Select To Previous Line",
	"Select To Next Line",
	"Toggle Escape Sequence Logging",
	"Send Custom Sequence To Terminal",
	"Create New Integrated Terminal Starting in a Custom Working Directory",
	"The directory to start the terminal at",
	"Rename the Currently Active Terminal",
	"The new name for the terminal",
	"No name argument provided",
	"Toggle Find Using Regex",
	"Toggle Find Using Whole Word",
	"Toggle Find Using Case Sensitive",
	"Find Next",
	"Find Previous",
	"Search Workspace",
	"Relaunch Active Terminal",
	"Show Environment Information",
	"Split Terminal",
	"Split Terminal",
	"Split Terminal (In Active Workspace)",
	"Select All",
	"Create New Integrated Terminal",
	"Select current working directory for new terminal",
	"New Terminal",
	"New Terminal",
	"Kill the Active Terminal Instance",
	"Kill Terminal",
	"Kill Terminal",
	"Kill Terminal",
	"Clear",
	"Select Default Profile",
	"Select Default Profile",
	"Configure Terminal Settings",
	"Configure Terminal Settings",
	"Copy Selection",
	"Copy",
	"Paste into Active Terminal",
	"Paste",
	"Paste Selection into Active Terminal",
	"Switch Terminal"
]);