/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'terminal.integrated.a11yPromptLabel',
	'terminal.integrated.a11yTooMuchOutput',
	'bellStatus',
	'keybindingHandling',
	'configureTerminalSettings',
	'yes',
	'no',
	'dontShowAgain',
	'terminal.slowRendering',
	'terminal.integrated.copySelection.noSelection',
	'disconnectStatus',
	'launchFailed.exitCodeAndCommandLine',
	'launchFailed.exitCodeOnly',
	'terminated.exitCodeAndCommandLine',
	'terminated.exitCodeOnly',
	'launchFailed.errorMessage',
	'terminalTextBoxAriaLabelNumberAndTitle',
	'terminalTextBoxAriaLabel',
	'terminalStaleTextBoxAriaLabel',
	'workbench.action.terminal.rename.prompt',
	'changeTerminalIcon',
	'changeIconTerminal',
	'renameTerminal',
	'configureTerminalTitle'
]);