/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'A summary of the settings. This label will be used in the settings file as separating comment.',
	'Description of the configuration properties.',
	'Property should not be empty.',
	"Configuration that can be configured only in the user settings.",
	"Configuration that can be configured only in the user settings or only in the remote settings.",
	"Configuration that can be configured in the user, remote or workspace settings.",
	"Configuration that can be configured in the user, remote, workspace or folder settings.",
	"Resource configuration that can be configured in language specific settings.",
	"Machine configuration that can be configured also in workspace or folder settings.",
	"Scope in which the configuration is applicable. Available scopes are `application`, `machine`, `window`, `resource`, and `machine-overridable`.",
	'Descriptions for enum values',
	'Descriptions for enum values in the markdown format.',
	'The description in the markdown format.',
	'If set, the property is marked as deprecated and the given message is shown as an explanation.',
	'If set, the property is marked as deprecated and the given message is shown as an explanation in the markdown format.',
	'Contributes default editor configuration settings by language.',
	"Language selector expected (e.g. [\"java\"])",
	"Cannot register configuration defaults for '{0}'. Only defaults for language specific settings are supported.",
	'Contributes configuration settings.',
	"'configuration.title' must be a string",
	"'configuration.properties' must be an object",
	"configuration.properties property '{0}' must be an object",
	"'configuration.allOf' is deprecated and should no longer be used. Instead, pass multiple configuration sections as an array to the 'configuration' contribution point.",
	"List of folders to be loaded in the workspace.",
	"A file path. e.g. `/root/folderA` or `./folderA` for a relative path that will be resolved against the location of the workspace file.",
	"An optional name for the folder. ",
	"URI of the folder",
	"An optional name for the folder. ",
	"Workspace settings",
	"Workspace launch configurations",
	"Workspace task configurations",
	"Workspace extensions",
	"The remote server where the workspace is located.",
	"Unknown workspace configuration property"
]);