/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Visual Studio Code",
	"Start",
	"New file",
	"Open folder...",
	"clone repository...",
	"Open folder...",
	"clone repository...",
	"Recent",
	"More...",
	"No recent folders",
	"Help",
	"Printable keyboard cheatsheet",
	"Introductory videos",
	"Tips and Tricks",
	"Product documentation",
	"GitHub repository",
	"Stack Overflow",
	"Join our Newsletter",
	"Show welcome page on startup",
	"Customize",
	"Tools and languages",
	"Install support for {0} and {1}",
	"Show more language extensions",
	"more",
	"Settings and keybindings",
	"Install the settings and keyboard shortcuts of {0} and {1}",
	"Show other keymap extensions",
	"others",
	"Color theme",
	"Make the editor and your code look the way you love",
	"Learn",
	"Find and run all commands",
	"Rapidly access and search commands from the Command Palette ({0})",
	"Interface overview",
	"Get a visual overlay highlighting the major components of the UI",
	"Interactive playground",
	"Try out essential editor features in a short walkthrough"
]);