/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Start without an editor.",
	"Open the Welcome page.",
	"Open the README when opening a folder that contains one, fallback to 'welcomePage' otherwise.",
	"Open a new untitled file (only applies when opening an empty window).",
	"Open the Welcome page when opening an empty workbench.",
	"Open the Getting Started page.",
	"Controls which editor is shown at startup, if none are restored from the previous session.",
	"Start without an editor.",
	"Open the Welcome page.",
	"Open the README when opening a folder that contains one, fallback to 'welcomePage' otherwise.",
	"Open a new untitled file (only applies when opening an empty window).",
	"Open the Welcome page when opening an empty workbench.",
	"Open the Getting Started page.",
	"Controls which editor is shown at startup, if none are restored from the previous session.",
	"Welcome",
	"JavaScript",
	"Python",
	"Java",
	"PHP",
	"Azure",
	"Show Azure extensions",
	"Docker",
	"Vim",
	"Sublime",
	"Atom",
	"Support for {0} is already installed.",
	"The window will reload after installing additional support for {0}.",
	"Installing additional support for {0}...",
	"Support for {0} with id {1} could not be found.",
	"The {0} keyboard shortcuts are already installed.",
	"The window will reload after installing the {0} keyboard shortcuts.",
	"Installing the {0} keyboard shortcuts...",
	"The {0} keyboard shortcuts with id {1} could not be found.",
	"Welcome",
	"Open folder {0} with path {1}",
	", ",
	"Install {0} keymap",
	"Install additional support for {0}",
	"{0} keymap is already installed",
	"{0} support is already installed",
	"OK",
	"Details"
]);