/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'workbench.startupEditor.none' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'workbench.startupEditor.welcomePage' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'workbench.startupEditor.readme' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'workbench.startupEditor.newUntitledFile' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'workbench.startupEditor.welcomePageInEmptyWorkbench' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'workbench.startupEditor.gettingStarted' },
	'workbench.startupEditor',
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'workbench.startupEditor.none' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'workbench.startupEditor.welcomePage' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'workbench.startupEditor.readme' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'workbench.startupEditor.newUntitledFile' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'workbench.startupEditor.welcomePageInEmptyWorkbench' },
	{ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'workbench.startupEditor.gettingStarted' },
	'workbench.startupEditor',
	'welcomePage',
	'welcomePage.javaScript',
	'welcomePage.python',
	'welcomePage.java',
	'welcomePage.php',
	'welcomePage.azure',
	'welcomePage.showAzureExtensions',
	'welcomePage.docker',
	'welcomePage.vim',
	'welcomePage.sublime',
	'welcomePage.atom',
	'welcomePage.extensionPackAlreadyInstalled',
	'welcomePage.willReloadAfterInstallingExtensionPack',
	'welcomePage.installingExtensionPack',
	'welcomePage.extensionPackNotFound',
	'welcomePage.keymapAlreadyInstalled',
	'welcomePage.willReloadAfterInstallingKeymap',
	'welcomePage.installingKeymap',
	'welcomePage.keymapNotFound',
	'welcome.title',
	'welcomePage.openFolderWithPath',
	'welcomePage.extensionListSeparator',
	'welcomePage.installKeymap',
	'welcomePage.installExtensionPack',
	'welcomePage.installedKeymap',
	'welcomePage.installedExtensionPack',
	'ok',
	'details'
]);