/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Whether the editor text has focus (cursor is blinking)",
	"Whether the editor or an editor widget has focus (e.g. focus is in the find widget)",
	"Whether an editor or a rich text input has focus (cursor is blinking)",
	"Whether the editor is read only",
	"Whether the context is a diff editor",
	"Whether `editor.columnSelection` is enabled",
	"Whether the editor has text selected",
	"Whether the editor has multiple selections",
	"Whether `Tab` will move focus out of the editor",
	"Whether the editor hover is visible",
	"Whether the editor is part of a larger editor (e.g. notebooks)",
	"The language identifier of the editor",
	"Whether the editor has a completion item provider",
	"Whether the editor has a code actions provider",
	"Whether the editor has a code lens provider",
	"Whether the editor has a definition provider",
	"Whether the editor has a declaration provider",
	"Whether the editor has an implementation provider",
	"Whether the editor has a type definition provider",
	"Whether the editor has a hover provider",
	"Whether the editor has a document highlight provider",
	"Whether the editor has a document symbol provider",
	"Whether the editor has a reference provider",
	"Whether the editor has a rename provider",
	"Whether the editor has a signature help provider",
	"Whether the editor has an inline hints provider",
	"Whether the editor has a document formatting provider",
	"Whether the editor has a document selection formatting provider",
	"Whether the editor has multiple document formatting providers",
	"Whether the editor has multiple document selection formatting providers"
]);