/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"No selection",
	"Line {0}, Column {1} ({2} selected)",
	"Line {0}, Column {1}",
	"{0} selections ({1} characters selected)",
	"{0} selections",
	"Now changing the setting `accessibilitySupport` to 'on'.",
	"Now opening the Editor Accessibility documentation page.",
	" in a read-only pane of a diff editor.",
	" in a pane of a diff editor.",
	" in a read-only code editor",
	" in a code editor",
	"To configure the editor to be optimized for usage with a Screen Reader press Command+E now.",
	"To configure the editor to be optimized for usage with a Screen Reader press Control+E now.",
	"The editor is configured to be optimized for usage with a Screen Reader.",
	"The editor is configured to never be optimized for usage with a Screen Reader, which is not the case at this time.",
	"Pressing Tab in the current editor will move focus to the next focusable element. Toggle this behavior by pressing {0}.",
	"Pressing Tab in the current editor will move focus to the next focusable element. The command {0} is currently not triggerable by a keybinding.",
	"Pressing Tab in the current editor will insert the tab character. Toggle this behavior by pressing {0}.",
	"Pressing Tab in the current editor will insert the tab character. The command {0} is currently not triggerable by a keybinding.",
	"Press Command+H now to open a browser window with more information related to editor accessibility.",
	"Press Control+H now to open a browser window with more information related to editor accessibility.",
	"You can dismiss this tooltip and return to the editor by pressing Escape or Shift+Escape.",
	"Show Accessibility Help",
	"Developer: Inspect Tokens",
	"Go to Line/Column...",
	"Show all Quick Access Providers",
	"Command Palette",
	"Show And Run Commands",
	"Go to Symbol...",
	"Go to Symbol by Category...",
	"Editor content",
	"Press Alt+F1 for Accessibility Options.",
	"Toggle High Contrast Theme",
	"Made {0} edits in {1} files"
]);